/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __SERVER_H__
#define __SERVER_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <smaccm_Server.h>
#include "input_Server_read_camera_data_monitor.h"
#include "input_Server_read_get_can_monitor.h"
#include "input_Server_read_get_input_monitor.h"
#include "ivory.h"
void component_entry(const int64_t *n_var0);
void component_init(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __SERVER_H__ */