/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.2
 */
#include <compacompa.h>
#include <smaccm_compa.h>

void caller(uint32_t time)
{
    LOIConfig n_local0 = {};
    LOIConfig* n_ref1 = &n_local0;
    
    *&n_ref1->vehicletype = (uint16_t) 1U;
    *&n_ref1->vehiclesubtype = (uint16_t) 2U;
    *&n_ref1->vehicleid = (int32_t) 3;
    printf("Calling doCall\n", (int32_t) 3);
    
    int32_t n_r2;
    aadl_do_doCall(n_ref1, &n_r2);
    
    printf("Returned %d\n", n_r2);
}