/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "output_Server_write_self2encrypt_monitor.h"

void callback_output_Server_write_self2encrypt_2(const uint8_t n_var0[80U])
{
    Server_write_self2encrypt(n_var0);
}