/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.2
 */
#include "uart_unbuffer_monitor.h"

bool flush_defer;

struct ivory_string_UARTBuffer buffer;

void callback_uart_byte_tosend(const uint8_t* n_var0)
{
    uint8_t n_deref0 = *n_var0;
    int32_t n_deref1 = buffer.ivory_string_UARTBuffer_len;
    
    if ((bool) (n_deref1 < (int32_t) 128)) {
        buffer.ivory_string_UARTBuffer_data[n_deref1 % 128] = n_deref0;
        buffer.ivory_string_UARTBuffer_len = (int32_t) (n_deref1 + (int32_t) 1);
    }
}

void callback_uart_tx_flush(const int64_t* n_var0)
{
    bool n_deref0 = flush_defer;
    int32_t n_deref1 = buffer.ivory_string_UARTBuffer_len;
    
    if ((bool) ((bool) (n_deref1 > (int32_t) 0) && (bool) !n_deref0)) {
        emitter_uart_tx_flush_chan_2(&buffer);
        buffer.ivory_string_UARTBuffer_len = (int32_t) 0;
        flush_defer = true;
    }
}

void callback_uart_tx_res(const bool* n_var0)
{
    flush_defer = false;
}