/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "frame_datalink_encode_monitor.h"

bool pending;

void callback_encoder_ct_in(const uint8_t n_var0[96U])
{
    bool n_deref0 = pending;
    
    if ((bool) !n_deref0) {
        uint8_t n_local1[96U] = {};
        uint8_t *n_ref2 = n_local1;
        
        for (int32_t n_ix3 = (int32_t) 0; n_ix3 <= (int32_t) 95; n_ix3++) {
            ivory_serialize_pack_uint8_be((uint8_t *) n_ref2, (uint32_t) n_ix3, &n_var0[n_ix3]);
        }
        
        struct ivory_string_HXCyphertext n_local4 = {};
        struct ivory_string_HXCyphertext *n_ref5 = &n_local4;
        const int32_t *n_cse15 = &n_ref5->ivory_string_HXCyphertext_len;
        int32_t n_deref6 = *n_cse15;
        int32_t n_deref7 = *n_cse15;
        
        ASSERTS((bool) (n_deref7 < (int32_t) 195));
        
        uint8_t *n_cse24 = n_ref5->ivory_string_HXCyphertext_data;
        
        n_cse24[n_deref7 % 195] = (uint8_t) 126U;
        
        int32_t *n_cse27 = &n_ref5->ivory_string_HXCyphertext_len;
        
        *n_cse27 = (int32_t) ((int32_t) 1 + n_deref7);
        
        int32_t n_deref8 = *n_cse15;
        
        ASSERTS((bool) (n_deref8 < (int32_t) 195));
        n_cse24[n_deref8 % 195] = (uint8_t) 0U;
        *n_cse27 = (int32_t) ((int32_t) 1 + n_deref8);
        for (int32_t n_ix9 = (int32_t) 0; n_ix9 <= (int32_t) 95; n_ix9++) {
            uint8_t n_deref10 = n_ref2[n_ix9];
            
            if ((bool) ((bool) ((uint8_t) 126U == n_deref10) || (bool) (n_deref10 == (uint8_t) 124U))) {
                int32_t n_deref11 = *n_cse15;
                
                ASSERTS((bool) (n_deref11 < (int32_t) 195));
                n_cse24[n_deref11 % 195] = (uint8_t) 124U;
                *n_cse27 = (int32_t) ((int32_t) 1 + n_deref11);
                
                int32_t n_deref12 = *n_cse15;
                
                ASSERTS((bool) (n_deref12 < (int32_t) 195));
                n_cse24[n_deref12 % 195] = (uint8_t) (n_deref10 ^ (uint8_t) 32U);
                *n_cse27 = (int32_t) ((int32_t) 1 + n_deref12);
            } else {
                int32_t n_deref13 = *n_cse15;
                
                ASSERTS((bool) (n_deref13 < (int32_t) 195));
                n_cse24[n_deref13 % 195] = n_deref10;
                *n_cse27 = (int32_t) ((int32_t) 1 + n_deref13);
            }
        }
        
        int32_t n_deref14 = *n_cse15;
        
        ASSERTS((bool) (n_deref14 < (int32_t) 195));
        n_cse24[n_deref14 % 195] = (uint8_t) 126U;
        *n_cse27 = (int32_t) ((int32_t) 1 + n_deref14);
        callback_output_UART_out_UART_hw_put_packet_2(n_ref5);
        pending = true;
    }
}

void callback_complete(const bool *n_var0)
{
    pending = false;
}