/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "hxstream_state_module.h"

uint8_t decodeSM(struct hxstream_state *n_var0, uint8_t n_var1)
{
    uint8_t n_deref0 = n_var0->fstate;
    uint8_t n_local1 = (uint8_t) 0U;
    uint8_t *n_ref2 = &n_local1;
    
    if ((bool) (n_var1 == (uint8_t) 126U)) {
        n_var0->offset = (int32_t) 0;
        
        uint8_t *n_cse3 = &n_var0->fstate;
        
        *n_cse3 = (uint8_t) 2U;
        n_var0->tagSeen = false;
        *n_cse3 = (uint8_t) 1U;
    } else {
        if ((bool) ((uint8_t) 1U == n_deref0)) {
            n_var0->ftag = n_var1;
            n_var0->tagSeen = true;
            n_var0->fstate = (uint8_t) 2U;
        } else {
            if ((bool) ((uint8_t) 2U == n_deref0)) {
                if ((bool) (n_var1 == (uint8_t) 124U)) {
                    n_var0->fstate = (uint8_t) 3U;
                } else {
                    int32_t n_deref3 = n_var0->offset;
                    
                    n_var0->offset = (int32_t) ((int32_t) 1 + n_deref3);
                    *n_ref2 = n_var1;
                }
            } else {
                if ((bool) (n_deref0 == (uint8_t) 3U)) {
                    n_var0->fstate = (uint8_t) 2U;
                    
                    int32_t n_deref4 = n_var0->offset;
                    
                    n_var0->offset = (int32_t) ((int32_t) 1 + n_deref4);
                    *n_ref2 = (uint8_t) (n_var1 ^ (uint8_t) 32U);
                }
            }
        }
    }
    
    uint8_t n_deref5 = *n_ref2;
    
    return n_deref5;
}