/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "output_UART_out_UART_hw_put_packet_monitor.h"
#include <smaccm_top_i_types.h>
#include "smaccm_Encrypt.h"

void callback_output_UART_out_UART_hw_put_packet_2(const struct ivory_string_HXCyphertext *n_var0)
{
    SMACCM_DATA__UART_Packet_i packet;
    packet.buf_len = n_var0->ivory_string_HXCyphertext_len;
    memcpy(packet.buf, n_var0->ivory_string_HXCyphertext_data, packet.buf_len);
    Encrypt_write_self2uart(&packet);
}
