/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __FLIGHTMODE_TYPE_H__
#define __FLIGHTMODE_TYPE_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
struct flightmode {
    uint8_t mode;
    uint32_t time;
} __attribute__((__packed__));

#ifdef __cplusplus
}
#endif
#endif /* __FLIGHTMODE_TYPE_H__ */