/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __IVORY_STDLIB_STRING_H__
#define __IVORY_STDLIB_STRING_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory_stdlib_string_prim.h>
#include <string.h>
#include "ivory.h"
bool ivory_string_eq(const uint8_t* n_var0, int32_t n_var1, const
                     uint8_t* n_var2, int32_t n_var3);

#ifdef __cplusplus
}
#endif
#endif /* __IVORY_STDLIB_STRING_H__ */