/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "mavlink_omnidirectional_flow_msg.h"

void mavlink_omnidirectional_flow_msg_send(const
                                           struct omnidirectional_flow_msg* n_var0,
                                           uint8_t* n_var1, uint8_t n_var2[80U])
{
    uint8_t n_local0[54U] = {};
    uint8_t* n_ref1 = n_local0;
    uint64_t n_deref2 = n_var0->time_usec;
    
    mavlink_pack_uint64_t((uint8_t*) n_ref1, 0U, n_deref2);
    
    float n_deref3 = n_var0->front_distance_m;
    
    mavlink_pack_float((uint8_t*) n_ref1, 8U, n_deref3);
    
    uint8_t n_deref4 = n_var0->sensor_id;
    
    mavlink_pack_uint8_t((uint8_t*) n_ref1, 52U, n_deref4);
    
    uint8_t n_deref5 = n_var0->quality;
    
    mavlink_pack_uint8_t((uint8_t*) n_ref1, 53U, n_deref5);
    
    const int16_t* n_let6 = n_var0->left;
    
    for (int32_t n_ix7 = 0; n_ix7 <= 9; n_ix7++) {
        int16_t n_deref8 = n_let6[n_ix7];
        
        mavlink_pack_int16_t((uint8_t*) n_ref1, 12U + (uint8_t) n_ix7,
                             n_deref8);
    }
    
    const int16_t* n_let9 = n_var0->right;
    
    for (int32_t n_ix10 = 0; n_ix10 <= 9; n_ix10++) {
        int16_t n_deref11 = n_let9[n_ix10];
        
        mavlink_pack_int16_t((uint8_t*) n_ref1, 32U + (uint8_t) n_ix10,
                             n_deref11);
    }
    for (int32_t n_ix12 = 0; n_ix12 <= 53; n_ix12++) {
        ASSERTS(n_ix12 > 0 && 2147483647 - n_ix12 >= 6 || n_ix12 <= 0);
        if (n_ix12 + 6 >= 80) { } else {
            uint8_t n_deref13 = n_ref1[n_ix12];
            
            ASSERTS(n_ix12 > 0 && 2147483641 >= n_ix12 || n_ix12 <= 0);
            ASSERTS(0 <= 6 + n_ix12 && 6 + n_ix12 < 80);
            *&n_var2[(6 + n_ix12) % 80] = n_deref13;
        }
    }
    mavlinkSendWithWriter(106U, 211U, 54U, n_var1, n_var2);
    for (int32_t n_ix14 = 0; n_ix14 <= 17; n_ix14++) {
        ASSERTS(n_ix14 > 0 && 2147483647 - n_ix14 >= 62 || n_ix14 <= 0);
        ASSERTS(0 <= n_ix14 + 62 && n_ix14 + 62 < 80);
        *&n_var2[(n_ix14 + 62) % 80] = 0U;
    }
    return;
}

void mavlink_omnidirectional_flow_unpack(struct omnidirectional_flow_msg* n_var0,
                                         const uint8_t* n_var1)
{
    uint64_t n_r0 = mavlink_unpack_uint64_t(n_var1, 0U);
    
    *&n_var0->time_usec = n_r0;
    
    float n_r1 = mavlink_unpack_float(n_var1, 8U);
    
    *&n_var0->front_distance_m = n_r1;
    
    uint8_t n_r2 = mavlink_unpack_uint8_t(n_var1, 52U);
    
    *&n_var0->sensor_id = n_r2;
    
    uint8_t n_r3 = mavlink_unpack_uint8_t(n_var1, 53U);
    
    *&n_var0->quality = n_r3;
    for (int32_t n_ix4 = 0; n_ix4 <= 9; n_ix4++) {
        int16_t n_r5 = mavlink_unpack_int16_t(n_var1, 12U + (uint8_t) n_ix4);
        
        *&n_var0->left[n_ix4] = n_r5;
    }
    for (int32_t n_ix6 = 0; n_ix6 <= 9; n_ix6++) {
        int16_t n_r7 = mavlink_unpack_int16_t(n_var1, 32U + (uint8_t) n_ix6);
        
        *&n_var0->right[n_ix6] = n_r7;
    }
}