/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __MAVLINK_GLOBAL_POSITION_INT_MSG_H__
#define __MAVLINK_GLOBAL_POSITION_INT_MSG_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "mavlinkSendModule.h"
#include "mavlink_pack_ivory.h"
struct global_position_int_msg {
    uint32_t time_boot_ms;
    int32_t lat;
    int32_t lon;
    int32_t alt;
    int32_t relative_alt;
    int16_t vx;
    int16_t vy;
    int16_t vz;
    uint16_t hdg;
} __attribute__((__packed__));
void mavlink_global_position_int_msg_send(const
                                          struct global_position_int_msg* n_var0,
                                          uint8_t* n_var1, uint8_t n_var2[80U]);
void mavlink_global_position_int_unpack(struct global_position_int_msg* n_var0,
                                        const uint8_t* n_var1);

#ifdef __cplusplus
}
#endif
#endif /* __MAVLINK_GLOBAL_POSITION_INT_MSG_H__ */