/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "mavlink_mission_item_msg.h"

void mavlink_mission_item_msg_send(const struct mission_item_msg* n_var0,
                                   uint8_t* n_var1, uint8_t n_var2[80U])
{
    uint8_t n_local0[37U] = {};
    uint8_t* n_ref1 = n_local0;
    float n_deref2 = n_var0->param1;
    
    mavlink_pack_float((uint8_t*) n_ref1, 0U, n_deref2);
    
    float n_deref3 = n_var0->param2;
    
    mavlink_pack_float((uint8_t*) n_ref1, 4U, n_deref3);
    
    float n_deref4 = n_var0->param3;
    
    mavlink_pack_float((uint8_t*) n_ref1, 8U, n_deref4);
    
    float n_deref5 = n_var0->param4;
    
    mavlink_pack_float((uint8_t*) n_ref1, 12U, n_deref5);
    
    float n_deref6 = n_var0->x;
    
    mavlink_pack_float((uint8_t*) n_ref1, 16U, n_deref6);
    
    float n_deref7 = n_var0->y;
    
    mavlink_pack_float((uint8_t*) n_ref1, 20U, n_deref7);
    
    float n_deref8 = n_var0->z;
    
    mavlink_pack_float((uint8_t*) n_ref1, 24U, n_deref8);
    
    uint16_t n_deref9 = n_var0->mission_item_seq;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 28U, n_deref9);
    
    uint16_t n_deref10 = n_var0->command;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 30U, n_deref10);
    
    uint8_t n_deref11 = n_var0->target_system;
    
    mavlink_pack_uint8_t((uint8_t*) n_ref1, 32U, n_deref11);
    
    uint8_t n_deref12 = n_var0->target_component;
    
    mavlink_pack_uint8_t((uint8_t*) n_ref1, 33U, n_deref12);
    
    uint8_t n_deref13 = n_var0->frame;
    
    mavlink_pack_uint8_t((uint8_t*) n_ref1, 34U, n_deref13);
    
    uint8_t n_deref14 = n_var0->current;
    
    mavlink_pack_uint8_t((uint8_t*) n_ref1, 35U, n_deref14);
    
    uint8_t n_deref15 = n_var0->autocontinue;
    
    mavlink_pack_uint8_t((uint8_t*) n_ref1, 36U, n_deref15);
    for (int32_t n_ix16 = 0; n_ix16 <= 36; n_ix16++) {
        ASSERTS(n_ix16 > 0 && 2147483647 - n_ix16 >= 6 || n_ix16 <= 0);
        if (n_ix16 + 6 >= 80) { } else {
            uint8_t n_deref17 = n_ref1[n_ix16];
            
            ASSERTS(n_ix16 > 0 && 2147483641 >= n_ix16 || n_ix16 <= 0);
            ASSERTS(0 <= 6 + n_ix16 && 6 + n_ix16 < 80);
            *&n_var2[(6 + n_ix16) % 80] = n_deref17;
        }
    }
    mavlinkSendWithWriter(39U, 254U, 37U, n_var1, n_var2);
    for (int32_t n_ix18 = 0; n_ix18 <= 34; n_ix18++) {
        ASSERTS(n_ix18 > 0 && 2147483647 - n_ix18 >= 45 || n_ix18 <= 0);
        ASSERTS(0 <= n_ix18 + 45 && n_ix18 + 45 < 80);
        *&n_var2[(n_ix18 + 45) % 80] = 0U;
    }
    return;
}

void mavlink_mission_item_unpack(struct mission_item_msg* n_var0, const
                                 uint8_t* n_var1)
{
    float n_r0 = mavlink_unpack_float(n_var1, 0U);
    
    *&n_var0->param1 = n_r0;
    
    float n_r1 = mavlink_unpack_float(n_var1, 4U);
    
    *&n_var0->param2 = n_r1;
    
    float n_r2 = mavlink_unpack_float(n_var1, 8U);
    
    *&n_var0->param3 = n_r2;
    
    float n_r3 = mavlink_unpack_float(n_var1, 12U);
    
    *&n_var0->param4 = n_r3;
    
    float n_r4 = mavlink_unpack_float(n_var1, 16U);
    
    *&n_var0->x = n_r4;
    
    float n_r5 = mavlink_unpack_float(n_var1, 20U);
    
    *&n_var0->y = n_r5;
    
    float n_r6 = mavlink_unpack_float(n_var1, 24U);
    
    *&n_var0->z = n_r6;
    
    uint16_t n_r7 = mavlink_unpack_uint16_t(n_var1, 28U);
    
    *&n_var0->mission_item_seq = n_r7;
    
    uint16_t n_r8 = mavlink_unpack_uint16_t(n_var1, 30U);
    
    *&n_var0->command = n_r8;
    
    uint8_t n_r9 = mavlink_unpack_uint8_t(n_var1, 32U);
    
    *&n_var0->target_system = n_r9;
    
    uint8_t n_r10 = mavlink_unpack_uint8_t(n_var1, 33U);
    
    *&n_var0->target_component = n_r10;
    
    uint8_t n_r11 = mavlink_unpack_uint8_t(n_var1, 34U);
    
    *&n_var0->frame = n_r11;
    
    uint8_t n_r12 = mavlink_unpack_uint8_t(n_var1, 35U);
    
    *&n_var0->current = n_r12;
    
    uint8_t n_r13 = mavlink_unpack_uint8_t(n_var1, 36U);
    
    *&n_var0->autocontinue = n_r13;
}