/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __MAVLINK_RC_CHANNELS_RAW_MSG_H__
#define __MAVLINK_RC_CHANNELS_RAW_MSG_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "mavlinkSendModule.h"
#include "mavlink_pack_ivory.h"
struct rc_channels_raw_msg {
    uint32_t time_boot_ms;
    uint16_t chan1_raw;
    uint16_t chan2_raw;
    uint16_t chan3_raw;
    uint16_t chan4_raw;
    uint16_t chan5_raw;
    uint16_t chan6_raw;
    uint16_t chan7_raw;
    uint16_t chan8_raw;
    uint8_t port;
    uint8_t rssi;
} __attribute__((__packed__));
void mavlink_rc_channels_raw_msg_send(const struct rc_channels_raw_msg* n_var0,
                                      uint8_t* n_var1, uint8_t n_var2[80U]);
void mavlink_rc_channels_raw_unpack(struct rc_channels_raw_msg* n_var0, const
                                    uint8_t* n_var1);

#ifdef __cplusplus
}
#endif
#endif /* __MAVLINK_RC_CHANNELS_RAW_MSG_H__ */