/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __MAVLINK_SET_LOCAL_POSITION_SETPOINT_MSG_H__
#define __MAVLINK_SET_LOCAL_POSITION_SETPOINT_MSG_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "mavlinkSendModule.h"
#include "mavlink_pack_ivory.h"
struct set_local_position_setpoint_msg {
    float x;
    float y;
    float z;
    float yaw;
    uint8_t target_system;
    uint8_t target_component;
    uint8_t coordinate_frame;
} __attribute__((__packed__));
void mavlink_set_local_position_setpoint_msg_send(const
                                                  struct set_local_position_setpoint_msg* n_var0,
                                                  uint8_t* n_var1,
                                                  uint8_t n_var2[80U]);
void mavlink_set_local_position_setpoint_unpack(struct set_local_position_setpoint_msg* n_var0,
                                                const uint8_t* n_var1);

#ifdef __cplusplus
}
#endif
#endif /* __MAVLINK_SET_LOCAL_POSITION_SETPOINT_MSG_H__ */