/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "mavlink_highres_imu_msg.h"

void mavlink_highres_imu_msg_send(const struct highres_imu_msg* n_var0,
                                  uint8_t* n_var1, uint8_t n_var2[80U])
{
    uint8_t n_local0[62U] = {};
    uint8_t* n_ref1 = n_local0;
    uint64_t n_deref2 = n_var0->time_usec;
    
    mavlink_pack_uint64_t((uint8_t*) n_ref1, 0U, n_deref2);
    
    float n_deref3 = n_var0->xacc;
    
    mavlink_pack_float((uint8_t*) n_ref1, 8U, n_deref3);
    
    float n_deref4 = n_var0->yacc;
    
    mavlink_pack_float((uint8_t*) n_ref1, 12U, n_deref4);
    
    float n_deref5 = n_var0->zacc;
    
    mavlink_pack_float((uint8_t*) n_ref1, 16U, n_deref5);
    
    float n_deref6 = n_var0->xgyro;
    
    mavlink_pack_float((uint8_t*) n_ref1, 20U, n_deref6);
    
    float n_deref7 = n_var0->ygyro;
    
    mavlink_pack_float((uint8_t*) n_ref1, 24U, n_deref7);
    
    float n_deref8 = n_var0->zgyro;
    
    mavlink_pack_float((uint8_t*) n_ref1, 28U, n_deref8);
    
    float n_deref9 = n_var0->xmag;
    
    mavlink_pack_float((uint8_t*) n_ref1, 32U, n_deref9);
    
    float n_deref10 = n_var0->ymag;
    
    mavlink_pack_float((uint8_t*) n_ref1, 36U, n_deref10);
    
    float n_deref11 = n_var0->zmag;
    
    mavlink_pack_float((uint8_t*) n_ref1, 40U, n_deref11);
    
    float n_deref12 = n_var0->abs_pressure;
    
    mavlink_pack_float((uint8_t*) n_ref1, 44U, n_deref12);
    
    float n_deref13 = n_var0->diff_pressure;
    
    mavlink_pack_float((uint8_t*) n_ref1, 48U, n_deref13);
    
    float n_deref14 = n_var0->pressure_alt;
    
    mavlink_pack_float((uint8_t*) n_ref1, 52U, n_deref14);
    
    float n_deref15 = n_var0->temperature;
    
    mavlink_pack_float((uint8_t*) n_ref1, 56U, n_deref15);
    
    uint16_t n_deref16 = n_var0->fields_updated;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 60U, n_deref16);
    for (int32_t n_ix17 = 0; n_ix17 <= 61; n_ix17++) {
        ASSERTS(n_ix17 > 0 && 2147483647 - n_ix17 >= 6 || n_ix17 <= 0);
        if (n_ix17 + 6 >= 80) { } else {
            uint8_t n_deref18 = n_ref1[n_ix17];
            
            ASSERTS(n_ix17 > 0 && 2147483641 >= n_ix17 || n_ix17 <= 0);
            ASSERTS(0 <= 6 + n_ix17 && 6 + n_ix17 < 80);
            *&n_var2[(6 + n_ix17) % 80] = n_deref18;
        }
    }
    mavlinkSendWithWriter(105U, 93U, 62U, n_var1, n_var2);
    for (int32_t n_ix19 = 0; n_ix19 <= 9; n_ix19++) {
        ASSERTS(n_ix19 > 0 && 2147483647 - n_ix19 >= 70 || n_ix19 <= 0);
        ASSERTS(0 <= n_ix19 + 70 && n_ix19 + 70 < 80);
        *&n_var2[(n_ix19 + 70) % 80] = 0U;
    }
    return;
}

void mavlink_highres_imu_unpack(struct highres_imu_msg* n_var0, const
                                uint8_t* n_var1)
{
    uint64_t n_r0 = mavlink_unpack_uint64_t(n_var1, 0U);
    
    *&n_var0->time_usec = n_r0;
    
    float n_r1 = mavlink_unpack_float(n_var1, 8U);
    
    *&n_var0->xacc = n_r1;
    
    float n_r2 = mavlink_unpack_float(n_var1, 12U);
    
    *&n_var0->yacc = n_r2;
    
    float n_r3 = mavlink_unpack_float(n_var1, 16U);
    
    *&n_var0->zacc = n_r3;
    
    float n_r4 = mavlink_unpack_float(n_var1, 20U);
    
    *&n_var0->xgyro = n_r4;
    
    float n_r5 = mavlink_unpack_float(n_var1, 24U);
    
    *&n_var0->ygyro = n_r5;
    
    float n_r6 = mavlink_unpack_float(n_var1, 28U);
    
    *&n_var0->zgyro = n_r6;
    
    float n_r7 = mavlink_unpack_float(n_var1, 32U);
    
    *&n_var0->xmag = n_r7;
    
    float n_r8 = mavlink_unpack_float(n_var1, 36U);
    
    *&n_var0->ymag = n_r8;
    
    float n_r9 = mavlink_unpack_float(n_var1, 40U);
    
    *&n_var0->zmag = n_r9;
    
    float n_r10 = mavlink_unpack_float(n_var1, 44U);
    
    *&n_var0->abs_pressure = n_r10;
    
    float n_r11 = mavlink_unpack_float(n_var1, 48U);
    
    *&n_var0->diff_pressure = n_r11;
    
    float n_r12 = mavlink_unpack_float(n_var1, 52U);
    
    *&n_var0->pressure_alt = n_r12;
    
    float n_r13 = mavlink_unpack_float(n_var1, 56U);
    
    *&n_var0->temperature = n_r13;
    
    uint16_t n_r14 = mavlink_unpack_uint16_t(n_var1, 60U);
    
    *&n_var0->fields_updated = n_r14;
}