/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __MAVLINKSENDMODULE_H__
#define __MAVLINKSENDMODULE_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "mavlink_crc.h"
void mavlinkSendWithWriter(uint8_t n_var0, uint8_t n_var1, uint8_t n_var2,
                           uint8_t* n_var3, uint8_t n_var4[80U]);

#ifdef __cplusplus
}
#endif
#endif /* __MAVLINKSENDMODULE_H__ */