/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __MAVLINK_HEARTBEAT_MSG_H__
#define __MAVLINK_HEARTBEAT_MSG_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "mavlinkSendModule.h"
#include "mavlink_pack_ivory.h"
struct heartbeat_msg {
    uint32_t custom_mode;
    uint8_t mavtype;
    uint8_t autopilot;
    uint8_t base_mode;
    uint8_t system_status;
    uint8_t mavlink_version;
} __attribute__((__packed__));
void mavlink_heartbeat_msg_send(const struct heartbeat_msg* n_var0,
                                uint8_t* n_var1, uint8_t n_var2[80U]);
void mavlink_heartbeat_unpack(struct heartbeat_msg* n_var0, const
                              uint8_t* n_var1);

#ifdef __cplusplus
}
#endif
#endif /* __MAVLINK_HEARTBEAT_MSG_H__ */