/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __MAVLINK_OMNIDIRECTIONAL_FLOW_MSG_H__
#define __MAVLINK_OMNIDIRECTIONAL_FLOW_MSG_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "mavlinkSendModule.h"
#include "mavlink_pack_ivory.h"
struct omnidirectional_flow_msg {
    uint64_t time_usec;
    float front_distance_m;
    uint8_t sensor_id;
    uint8_t quality;
    int16_t left[10U];
    int16_t right[10U];
} __attribute__((__packed__));
void mavlink_omnidirectional_flow_msg_send(const
                                           struct omnidirectional_flow_msg* n_var0,
                                           uint8_t* n_var1,
                                           uint8_t n_var2[80U]);
void mavlink_omnidirectional_flow_unpack(struct omnidirectional_flow_msg* n_var0,
                                         const uint8_t* n_var1);

#ifdef __cplusplus
}
#endif
#endif /* __MAVLINK_OMNIDIRECTIONAL_FLOW_MSG_H__ */