/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __MAVLINK_SYSTEM_TIME_MSG_H__
#define __MAVLINK_SYSTEM_TIME_MSG_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "mavlinkSendModule.h"
#include "mavlink_pack_ivory.h"
struct system_time_msg {
    uint64_t time_unix_usec;
    uint32_t time_boot_ms;
} __attribute__((__packed__));
void mavlink_system_time_msg_send(const struct system_time_msg* n_var0,
                                  uint8_t* n_var1, uint8_t n_var2[80U]);
void mavlink_system_time_unpack(struct system_time_msg* n_var0, const
                                uint8_t* n_var1);

#ifdef __cplusplus
}
#endif
#endif /* __MAVLINK_SYSTEM_TIME_MSG_H__ */