/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "mavlink_battery_status_msg.h"

void mavlink_battery_status_msg_send(const struct battery_status_msg* n_var0,
                                     uint8_t* n_var1, uint8_t n_var2[80U])
{
    uint8_t n_local0[16U] = {};
    uint8_t* n_ref1 = n_local0;
    uint16_t n_deref2 = n_var0->voltage_cell_1;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 0U, n_deref2);
    
    uint16_t n_deref3 = n_var0->voltage_cell_2;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 2U, n_deref3);
    
    uint16_t n_deref4 = n_var0->voltage_cell_3;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 4U, n_deref4);
    
    uint16_t n_deref5 = n_var0->voltage_cell_4;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 6U, n_deref5);
    
    uint16_t n_deref6 = n_var0->voltage_cell_5;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 8U, n_deref6);
    
    uint16_t n_deref7 = n_var0->voltage_cell_6;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 10U, n_deref7);
    
    int16_t n_deref8 = n_var0->current_battery;
    
    mavlink_pack_int16_t((uint8_t*) n_ref1, 12U, n_deref8);
    
    uint8_t n_deref9 = n_var0->accu_id;
    
    mavlink_pack_uint8_t((uint8_t*) n_ref1, 14U, n_deref9);
    
    int8_t n_deref10 = n_var0->battery_remaining;
    
    mavlink_pack_int8_t((uint8_t*) n_ref1, 15U, n_deref10);
    for (int32_t n_ix11 = 0; n_ix11 <= 15; n_ix11++) {
        ASSERTS(n_ix11 > 0 && 2147483647 - n_ix11 >= 6 || n_ix11 <= 0);
        if (n_ix11 + 6 >= 80) { } else {
            uint8_t n_deref12 = n_ref1[n_ix11];
            
            ASSERTS(n_ix11 > 0 && 2147483641 >= n_ix11 || n_ix11 <= 0);
            ASSERTS(0 <= 6 + n_ix11 && 6 + n_ix11 < 80);
            *&n_var2[(6 + n_ix11) % 80] = n_deref12;
        }
    }
    mavlinkSendWithWriter(147U, 42U, 16U, n_var1, n_var2);
    for (int32_t n_ix13 = 0; n_ix13 <= 55; n_ix13++) {
        ASSERTS(n_ix13 > 0 && 2147483647 - n_ix13 >= 24 || n_ix13 <= 0);
        ASSERTS(0 <= n_ix13 + 24 && n_ix13 + 24 < 80);
        *&n_var2[(n_ix13 + 24) % 80] = 0U;
    }
    return;
}

void mavlink_battery_status_unpack(struct battery_status_msg* n_var0, const
                                   uint8_t* n_var1)
{
    uint16_t n_r0 = mavlink_unpack_uint16_t(n_var1, 0U);
    
    *&n_var0->voltage_cell_1 = n_r0;
    
    uint16_t n_r1 = mavlink_unpack_uint16_t(n_var1, 2U);
    
    *&n_var0->voltage_cell_2 = n_r1;
    
    uint16_t n_r2 = mavlink_unpack_uint16_t(n_var1, 4U);
    
    *&n_var0->voltage_cell_3 = n_r2;
    
    uint16_t n_r3 = mavlink_unpack_uint16_t(n_var1, 6U);
    
    *&n_var0->voltage_cell_4 = n_r3;
    
    uint16_t n_r4 = mavlink_unpack_uint16_t(n_var1, 8U);
    
    *&n_var0->voltage_cell_5 = n_r4;
    
    uint16_t n_r5 = mavlink_unpack_uint16_t(n_var1, 10U);
    
    *&n_var0->voltage_cell_6 = n_r5;
    
    int16_t n_r6 = mavlink_unpack_int16_t(n_var1, 12U);
    
    *&n_var0->current_battery = n_r6;
    
    uint8_t n_r7 = mavlink_unpack_uint8_t(n_var1, 14U);
    
    *&n_var0->accu_id = n_r7;
    
    int8_t n_r8 = mavlink_unpack_int8_t(n_var1, 15U);
    
    *&n_var0->battery_remaining = n_r8;
}