/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "mavlinkSendModule.h"

void mavlinkSendWithWriter(uint8_t n_var0, uint8_t n_var1, uint8_t n_var2,
                           uint8_t* n_var3, uint8_t n_var4[80U])
{
    uint8_t n_deref0 = *n_var3;
    uint8_t n_local1[6U] = {254U, n_var2, n_deref0, 1U, 0U, n_var0};
    uint8_t* n_ref2 = n_local1;
    
    if (n_deref0 == 255U) {
        *n_var3 = 0U;
    } else {
        ASSERTS(255U - n_deref0 >= 1U);
        *n_var3 = n_deref0 + 1U;
    }
    for (int32_t n_ix3 = 0; n_ix3 <= 5; n_ix3++) {
        ASSERTS(n_ix3 >= 0 || n_ix3 <= 0);
        if (n_ix3 + 0 >= 80) { } else {
            uint8_t n_deref4 = n_ref2[n_ix3];
            
            ASSERTS(n_ix3 <= 0 || n_ix3 >= 0);
            ASSERTS(0 <= 0 + n_ix3 && 0 + n_ix3 < 80);
            *&n_var4[(0 + n_ix3) % 80] = n_deref4;
        }
    }
    
    uint16_t n_local5 = 65535U;
    uint16_t* n_ref6 = &n_local5;
    
    ASSERTS(6 + n_var2 - 1 < 80 && -1 <= 6 + n_var2 - 1);
    ASSERTS(6 + n_var2 < 0 && 2147483646 + (6 + n_var2) >= 0 || 6 + n_var2 >=
        0);
    ASSERTS(n_var2 > 0 && 2147483641 >= n_var2 || n_var2 <= 0);
    for (int32_t n_ix7 = 0; n_ix7 <= (6 + n_var2 - 1) % 80; n_ix7++) {
        if (n_ix7 == 0) { } else {
            uint8_t n_deref8 = n_var4[n_ix7];
            
            mavlink_crc_accumulate(n_deref8, n_ref6);
        }
    }
    mavlink_crc_accumulate(n_var1, n_ref6);
    
    uint16_t n_deref9 = *n_ref6;
    
    ASSERTS(80U > 6U + n_var2 + 1U);
    ASSERTS(n_var2 > 0 && 2147483641 >= n_var2 || n_var2 <= 0);
    ASSERTS(0 <= 6 + n_var2 && 6 + n_var2 < 80);
    *&n_var4[(6 + n_var2) % 80] = (uint8_t) (n_deref9 & 255U);
    ASSERTS(6 + n_var2 > 0 && 2147483647 - (6 + n_var2) >= 1 || 6 + n_var2 <=
        0);
    ASSERTS(n_var2 > 0 && 2147483641 >= n_var2 || n_var2 <= 0);
    ASSERTS(0 <= 6 + n_var2 + 1 && 6 + n_var2 + 1 < 80);
    *&n_var4[(6 + n_var2 + 1) % 80] = (uint8_t) (n_deref9 >> 8U & 255U);
}