/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __MAVLINK_LOCAL_POSITION_NED_MSG_H__
#define __MAVLINK_LOCAL_POSITION_NED_MSG_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "mavlinkSendModule.h"
#include "mavlink_pack_ivory.h"
struct local_position_ned_msg {
    uint32_t time_boot_ms;
    float x;
    float y;
    float z;
    float vx;
    float vy;
    float vz;
} __attribute__((__packed__));
void mavlink_local_position_ned_msg_send(const
                                         struct local_position_ned_msg* n_var0,
                                         uint8_t* n_var1, uint8_t n_var2[80U]);
void mavlink_local_position_ned_unpack(struct local_position_ned_msg* n_var0,
                                       const uint8_t* n_var1);

#ifdef __cplusplus
}
#endif
#endif /* __MAVLINK_LOCAL_POSITION_NED_MSG_H__ */