/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __MAVLINK_MANUAL_CONTROL_MSG_H__
#define __MAVLINK_MANUAL_CONTROL_MSG_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "mavlinkSendModule.h"
#include "mavlink_pack_ivory.h"
struct manual_control_msg {
    int16_t x;
    int16_t y;
    int16_t z;
    int16_t r;
    uint16_t buttons;
    uint8_t target;
} __attribute__((__packed__));
void mavlink_manual_control_msg_send(const struct manual_control_msg* n_var0,
                                     uint8_t* n_var1, uint8_t n_var2[80U]);
void mavlink_manual_control_unpack(struct manual_control_msg* n_var0, const
                                   uint8_t* n_var1);

#ifdef __cplusplus
}
#endif
#endif /* __MAVLINK_MANUAL_CONTROL_MSG_H__ */