/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "mavlink_request_data_stream_msg.h"

void mavlink_request_data_stream_msg_send(const
                                          struct request_data_stream_msg* n_var0,
                                          uint8_t* n_var1, uint8_t n_var2[80U])
{
    uint8_t n_local0[6U] = {};
    uint8_t* n_ref1 = n_local0;
    uint16_t n_deref2 = n_var0->req_message_rate;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 0U, n_deref2);
    
    uint8_t n_deref3 = n_var0->target_system;
    
    mavlink_pack_uint8_t((uint8_t*) n_ref1, 2U, n_deref3);
    
    uint8_t n_deref4 = n_var0->target_component;
    
    mavlink_pack_uint8_t((uint8_t*) n_ref1, 3U, n_deref4);
    
    uint8_t n_deref5 = n_var0->req_stream_id;
    
    mavlink_pack_uint8_t((uint8_t*) n_ref1, 4U, n_deref5);
    
    uint8_t n_deref6 = n_var0->start_stop;
    
    mavlink_pack_uint8_t((uint8_t*) n_ref1, 5U, n_deref6);
    for (int32_t n_ix7 = 0; n_ix7 <= 5; n_ix7++) {
        ASSERTS(n_ix7 > 0 && 2147483647 - n_ix7 >= 6 || n_ix7 <= 0);
        if (n_ix7 + 6 >= 80) { } else {
            uint8_t n_deref8 = n_ref1[n_ix7];
            
            ASSERTS(n_ix7 > 0 && 2147483641 >= n_ix7 || n_ix7 <= 0);
            ASSERTS(0 <= 6 + n_ix7 && 6 + n_ix7 < 80);
            *&n_var2[(6 + n_ix7) % 80] = n_deref8;
        }
    }
    mavlinkSendWithWriter(66U, 148U, 6U, n_var1, n_var2);
    for (int32_t n_ix9 = 0; n_ix9 <= 65; n_ix9++) {
        ASSERTS(n_ix9 > 0 && 2147483647 - n_ix9 >= 14 || n_ix9 <= 0);
        ASSERTS(0 <= n_ix9 + 14 && n_ix9 + 14 < 80);
        *&n_var2[(n_ix9 + 14) % 80] = 0U;
    }
    return;
}

void mavlink_request_data_stream_unpack(struct request_data_stream_msg* n_var0,
                                        const uint8_t* n_var1)
{
    uint16_t n_r0 = mavlink_unpack_uint16_t(n_var1, 0U);
    
    *&n_var0->req_message_rate = n_r0;
    
    uint8_t n_r1 = mavlink_unpack_uint8_t(n_var1, 2U);
    
    *&n_var0->target_system = n_r1;
    
    uint8_t n_r2 = mavlink_unpack_uint8_t(n_var1, 3U);
    
    *&n_var0->target_component = n_r2;
    
    uint8_t n_r3 = mavlink_unpack_uint8_t(n_var1, 4U);
    
    *&n_var0->req_stream_id = n_r3;
    
    uint8_t n_r4 = mavlink_unpack_uint8_t(n_var1, 5U);
    
    *&n_var0->start_stop = n_r4;
}