/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __MAVLINK_VFR_HUD_MSG_H__
#define __MAVLINK_VFR_HUD_MSG_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "mavlinkSendModule.h"
#include "mavlink_pack_ivory.h"
struct vfr_hud_msg {
    float airspeed;
    float groundspeed;
    float alt;
    float climb;
    int16_t heading;
    uint16_t throttle;
} __attribute__((__packed__));
void mavlink_vfr_hud_msg_send(const struct vfr_hud_msg* n_var0, uint8_t* n_var1,
                              uint8_t n_var2[80U]);
void mavlink_vfr_hud_unpack(struct vfr_hud_msg* n_var0, const uint8_t* n_var1);

#ifdef __cplusplus
}
#endif
#endif /* __MAVLINK_VFR_HUD_MSG_H__ */