/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "mavlink_crc.h"

void mavlink_crc_accumulate(uint8_t n_var0, uint16_t* n_var1)
{
    uint16_t n_deref0 = *n_var1;
    uint8_t n_let1 = n_var0 ^ (uint8_t) (n_deref0 & 255U);
    uint8_t n_let2 = n_let1 << 4U;
    uint8_t n_let3 = n_let1 ^ n_let2;
    uint16_t n_let4 = (uint16_t) n_let3 << 8U;
    uint16_t n_let5 = (uint16_t) n_let3 << 3U;
    uint16_t n_let6 = (uint16_t) n_let3 >> 4U;
    uint16_t n_let7 = n_deref0 >> 8U;
    uint16_t n_let8 = n_let7 ^ n_let4 ^ n_let5 ^ n_let6;
    
    *n_var1 = n_let8;
    return;
}