/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "mavlink_state_correction_msg.h"

void mavlink_state_correction_msg_send(const
                                       struct state_correction_msg* n_var0,
                                       uint8_t* n_var1, uint8_t n_var2[80U])
{
    uint8_t n_local0[36U] = {};
    uint8_t* n_ref1 = n_local0;
    float n_deref2 = n_var0->xErr;
    
    mavlink_pack_float((uint8_t*) n_ref1, 0U, n_deref2);
    
    float n_deref3 = n_var0->yErr;
    
    mavlink_pack_float((uint8_t*) n_ref1, 4U, n_deref3);
    
    float n_deref4 = n_var0->zErr;
    
    mavlink_pack_float((uint8_t*) n_ref1, 8U, n_deref4);
    
    float n_deref5 = n_var0->rollErr;
    
    mavlink_pack_float((uint8_t*) n_ref1, 12U, n_deref5);
    
    float n_deref6 = n_var0->pitchErr;
    
    mavlink_pack_float((uint8_t*) n_ref1, 16U, n_deref6);
    
    float n_deref7 = n_var0->yawErr;
    
    mavlink_pack_float((uint8_t*) n_ref1, 20U, n_deref7);
    
    float n_deref8 = n_var0->vxErr;
    
    mavlink_pack_float((uint8_t*) n_ref1, 24U, n_deref8);
    
    float n_deref9 = n_var0->vyErr;
    
    mavlink_pack_float((uint8_t*) n_ref1, 28U, n_deref9);
    
    float n_deref10 = n_var0->vzErr;
    
    mavlink_pack_float((uint8_t*) n_ref1, 32U, n_deref10);
    for (int32_t n_ix11 = 0; n_ix11 <= 35; n_ix11++) {
        ASSERTS(n_ix11 > 0 && 2147483647 - n_ix11 >= 6 || n_ix11 <= 0);
        if (n_ix11 + 6 >= 80) { } else {
            uint8_t n_deref12 = n_ref1[n_ix11];
            
            ASSERTS(n_ix11 > 0 && 2147483641 >= n_ix11 || n_ix11 <= 0);
            ASSERTS(0 <= 6 + n_ix11 && 6 + n_ix11 < 80);
            *&n_var2[(6 + n_ix11) % 80] = n_deref12;
        }
    }
    mavlinkSendWithWriter(64U, 130U, 36U, n_var1, n_var2);
    for (int32_t n_ix13 = 0; n_ix13 <= 35; n_ix13++) {
        ASSERTS(n_ix13 > 0 && 2147483647 - n_ix13 >= 44 || n_ix13 <= 0);
        ASSERTS(0 <= n_ix13 + 44 && n_ix13 + 44 < 80);
        *&n_var2[(n_ix13 + 44) % 80] = 0U;
    }
    return;
}

void mavlink_state_correction_unpack(struct state_correction_msg* n_var0, const
                                     uint8_t* n_var1)
{
    float n_r0 = mavlink_unpack_float(n_var1, 0U);
    
    *&n_var0->xErr = n_r0;
    
    float n_r1 = mavlink_unpack_float(n_var1, 4U);
    
    *&n_var0->yErr = n_r1;
    
    float n_r2 = mavlink_unpack_float(n_var1, 8U);
    
    *&n_var0->zErr = n_r2;
    
    float n_r3 = mavlink_unpack_float(n_var1, 12U);
    
    *&n_var0->rollErr = n_r3;
    
    float n_r4 = mavlink_unpack_float(n_var1, 16U);
    
    *&n_var0->pitchErr = n_r4;
    
    float n_r5 = mavlink_unpack_float(n_var1, 20U);
    
    *&n_var0->yawErr = n_r5;
    
    float n_r6 = mavlink_unpack_float(n_var1, 24U);
    
    *&n_var0->vxErr = n_r6;
    
    float n_r7 = mavlink_unpack_float(n_var1, 28U);
    
    *&n_var0->vyErr = n_r7;
    
    float n_r8 = mavlink_unpack_float(n_var1, 32U);
    
    *&n_var0->vzErr = n_r8;
}