/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __MAVLINK_OPTICAL_FLOW_MSG_H__
#define __MAVLINK_OPTICAL_FLOW_MSG_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "mavlinkSendModule.h"
#include "mavlink_pack_ivory.h"
struct optical_flow_msg {
    uint64_t time_usec;
    float flow_comp_m_x;
    float flow_comp_m_y;
    float ground_distance;
    int16_t flow_x;
    int16_t flow_y;
    uint8_t sensor_id;
    uint8_t quality;
} __attribute__((__packed__));
void mavlink_optical_flow_msg_send(const struct optical_flow_msg* n_var0,
                                   uint8_t* n_var1, uint8_t n_var2[80U]);
void mavlink_optical_flow_unpack(struct optical_flow_msg* n_var0, const
                                 uint8_t* n_var1);

#ifdef __cplusplus
}
#endif
#endif /* __MAVLINK_OPTICAL_FLOW_MSG_H__ */