/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "mavlink_set_mode_msg.h"

void mavlink_set_mode_msg_send(const struct set_mode_msg* n_var0,
                               uint8_t* n_var1, uint8_t n_var2[80U])
{
    uint8_t n_local0[6U] = {};
    uint8_t* n_ref1 = n_local0;
    uint32_t n_deref2 = n_var0->custom_mode;
    
    mavlink_pack_uint32_t((uint8_t*) n_ref1, 0U, n_deref2);
    
    uint8_t n_deref3 = n_var0->target_system;
    
    mavlink_pack_uint8_t((uint8_t*) n_ref1, 4U, n_deref3);
    
    uint8_t n_deref4 = n_var0->base_mode;
    
    mavlink_pack_uint8_t((uint8_t*) n_ref1, 5U, n_deref4);
    for (int32_t n_ix5 = 0; n_ix5 <= 5; n_ix5++) {
        ASSERTS(n_ix5 > 0 && 2147483647 - n_ix5 >= 6 || n_ix5 <= 0);
        if (n_ix5 + 6 >= 80) { } else {
            uint8_t n_deref6 = n_ref1[n_ix5];
            
            ASSERTS(n_ix5 > 0 && 2147483641 >= n_ix5 || n_ix5 <= 0);
            ASSERTS(0 <= 6 + n_ix5 && 6 + n_ix5 < 80);
            *&n_var2[(6 + n_ix5) % 80] = n_deref6;
        }
    }
    mavlinkSendWithWriter(11U, 89U, 6U, n_var1, n_var2);
    for (int32_t n_ix7 = 0; n_ix7 <= 65; n_ix7++) {
        ASSERTS(n_ix7 > 0 && 2147483647 - n_ix7 >= 14 || n_ix7 <= 0);
        ASSERTS(0 <= n_ix7 + 14 && n_ix7 + 14 < 80);
        *&n_var2[(n_ix7 + 14) % 80] = 0U;
    }
    return;
}

void mavlink_set_mode_unpack(struct set_mode_msg* n_var0, const uint8_t* n_var1)
{
    uint32_t n_r0 = mavlink_unpack_uint32_t(n_var1, 0U);
    
    *&n_var0->custom_mode = n_r0;
    
    uint8_t n_r1 = mavlink_unpack_uint8_t(n_var1, 4U);
    
    *&n_var0->target_system = n_r1;
    
    uint8_t n_r2 = mavlink_unpack_uint8_t(n_var1, 5U);
    
    *&n_var0->base_mode = n_r2;
}