/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "mavlink_hil_rc_inputs_raw_msg.h"

void mavlink_hil_rc_inputs_raw_msg_send(const
                                        struct hil_rc_inputs_raw_msg* n_var0,
                                        uint8_t* n_var1, uint8_t n_var2[80U])
{
    uint8_t n_local0[33U] = {};
    uint8_t* n_ref1 = n_local0;
    uint64_t n_deref2 = n_var0->time_usec;
    
    mavlink_pack_uint64_t((uint8_t*) n_ref1, 0U, n_deref2);
    
    uint16_t n_deref3 = n_var0->chan1_raw;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 8U, n_deref3);
    
    uint16_t n_deref4 = n_var0->chan2_raw;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 10U, n_deref4);
    
    uint16_t n_deref5 = n_var0->chan3_raw;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 12U, n_deref5);
    
    uint16_t n_deref6 = n_var0->chan4_raw;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 14U, n_deref6);
    
    uint16_t n_deref7 = n_var0->chan5_raw;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 16U, n_deref7);
    
    uint16_t n_deref8 = n_var0->chan6_raw;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 18U, n_deref8);
    
    uint16_t n_deref9 = n_var0->chan7_raw;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 20U, n_deref9);
    
    uint16_t n_deref10 = n_var0->chan8_raw;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 22U, n_deref10);
    
    uint16_t n_deref11 = n_var0->chan9_raw;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 24U, n_deref11);
    
    uint16_t n_deref12 = n_var0->chan10_raw;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 26U, n_deref12);
    
    uint16_t n_deref13 = n_var0->chan11_raw;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 28U, n_deref13);
    
    uint16_t n_deref14 = n_var0->chan12_raw;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 30U, n_deref14);
    
    uint8_t n_deref15 = n_var0->rssi;
    
    mavlink_pack_uint8_t((uint8_t*) n_ref1, 32U, n_deref15);
    for (int32_t n_ix16 = 0; n_ix16 <= 32; n_ix16++) {
        ASSERTS(n_ix16 > 0 && 2147483647 - n_ix16 >= 6 || n_ix16 <= 0);
        if (n_ix16 + 6 >= 80) { } else {
            uint8_t n_deref17 = n_ref1[n_ix16];
            
            ASSERTS(n_ix16 > 0 && 2147483641 >= n_ix16 || n_ix16 <= 0);
            ASSERTS(0 <= 6 + n_ix16 && 6 + n_ix16 < 80);
            *&n_var2[(6 + n_ix16) % 80] = n_deref17;
        }
    }
    mavlinkSendWithWriter(92U, 54U, 33U, n_var1, n_var2);
    for (int32_t n_ix18 = 0; n_ix18 <= 38; n_ix18++) {
        ASSERTS(n_ix18 > 0 && 2147483647 - n_ix18 >= 41 || n_ix18 <= 0);
        ASSERTS(0 <= n_ix18 + 41 && n_ix18 + 41 < 80);
        *&n_var2[(n_ix18 + 41) % 80] = 0U;
    }
    return;
}

void mavlink_hil_rc_inputs_raw_unpack(struct hil_rc_inputs_raw_msg* n_var0,
                                      const uint8_t* n_var1)
{
    uint64_t n_r0 = mavlink_unpack_uint64_t(n_var1, 0U);
    
    *&n_var0->time_usec = n_r0;
    
    uint16_t n_r1 = mavlink_unpack_uint16_t(n_var1, 8U);
    
    *&n_var0->chan1_raw = n_r1;
    
    uint16_t n_r2 = mavlink_unpack_uint16_t(n_var1, 10U);
    
    *&n_var0->chan2_raw = n_r2;
    
    uint16_t n_r3 = mavlink_unpack_uint16_t(n_var1, 12U);
    
    *&n_var0->chan3_raw = n_r3;
    
    uint16_t n_r4 = mavlink_unpack_uint16_t(n_var1, 14U);
    
    *&n_var0->chan4_raw = n_r4;
    
    uint16_t n_r5 = mavlink_unpack_uint16_t(n_var1, 16U);
    
    *&n_var0->chan5_raw = n_r5;
    
    uint16_t n_r6 = mavlink_unpack_uint16_t(n_var1, 18U);
    
    *&n_var0->chan6_raw = n_r6;
    
    uint16_t n_r7 = mavlink_unpack_uint16_t(n_var1, 20U);
    
    *&n_var0->chan7_raw = n_r7;
    
    uint16_t n_r8 = mavlink_unpack_uint16_t(n_var1, 22U);
    
    *&n_var0->chan8_raw = n_r8;
    
    uint16_t n_r9 = mavlink_unpack_uint16_t(n_var1, 24U);
    
    *&n_var0->chan9_raw = n_r9;
    
    uint16_t n_r10 = mavlink_unpack_uint16_t(n_var1, 26U);
    
    *&n_var0->chan10_raw = n_r10;
    
    uint16_t n_r11 = mavlink_unpack_uint16_t(n_var1, 28U);
    
    *&n_var0->chan11_raw = n_r11;
    
    uint16_t n_r12 = mavlink_unpack_uint16_t(n_var1, 30U);
    
    *&n_var0->chan12_raw = n_r12;
    
    uint8_t n_r13 = mavlink_unpack_uint8_t(n_var1, 32U);
    
    *&n_var0->rssi = n_r13;
}