/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "mavlink_scaled_imu_msg.h"

void mavlink_scaled_imu_msg_send(const struct scaled_imu_msg* n_var0,
                                 uint8_t* n_var1, uint8_t n_var2[80U])
{
    uint8_t n_local0[22U] = {};
    uint8_t* n_ref1 = n_local0;
    uint32_t n_deref2 = n_var0->time_boot_ms;
    
    mavlink_pack_uint32_t((uint8_t*) n_ref1, 0U, n_deref2);
    
    int16_t n_deref3 = n_var0->xacc;
    
    mavlink_pack_int16_t((uint8_t*) n_ref1, 4U, n_deref3);
    
    int16_t n_deref4 = n_var0->yacc;
    
    mavlink_pack_int16_t((uint8_t*) n_ref1, 6U, n_deref4);
    
    int16_t n_deref5 = n_var0->zacc;
    
    mavlink_pack_int16_t((uint8_t*) n_ref1, 8U, n_deref5);
    
    int16_t n_deref6 = n_var0->xgyro;
    
    mavlink_pack_int16_t((uint8_t*) n_ref1, 10U, n_deref6);
    
    int16_t n_deref7 = n_var0->ygyro;
    
    mavlink_pack_int16_t((uint8_t*) n_ref1, 12U, n_deref7);
    
    int16_t n_deref8 = n_var0->zgyro;
    
    mavlink_pack_int16_t((uint8_t*) n_ref1, 14U, n_deref8);
    
    int16_t n_deref9 = n_var0->xmag;
    
    mavlink_pack_int16_t((uint8_t*) n_ref1, 16U, n_deref9);
    
    int16_t n_deref10 = n_var0->ymag;
    
    mavlink_pack_int16_t((uint8_t*) n_ref1, 18U, n_deref10);
    
    int16_t n_deref11 = n_var0->zmag;
    
    mavlink_pack_int16_t((uint8_t*) n_ref1, 20U, n_deref11);
    for (int32_t n_ix12 = 0; n_ix12 <= 21; n_ix12++) {
        ASSERTS(n_ix12 > 0 && 2147483647 - n_ix12 >= 6 || n_ix12 <= 0);
        if (n_ix12 + 6 >= 80) { } else {
            uint8_t n_deref13 = n_ref1[n_ix12];
            
            ASSERTS(n_ix12 > 0 && 2147483641 >= n_ix12 || n_ix12 <= 0);
            ASSERTS(0 <= 6 + n_ix12 && 6 + n_ix12 < 80);
            *&n_var2[(6 + n_ix12) % 80] = n_deref13;
        }
    }
    mavlinkSendWithWriter(26U, 170U, 22U, n_var1, n_var2);
    for (int32_t n_ix14 = 0; n_ix14 <= 49; n_ix14++) {
        ASSERTS(n_ix14 > 0 && 2147483647 - n_ix14 >= 30 || n_ix14 <= 0);
        ASSERTS(0 <= n_ix14 + 30 && n_ix14 + 30 < 80);
        *&n_var2[(n_ix14 + 30) % 80] = 0U;
    }
    return;
}

void mavlink_scaled_imu_unpack(struct scaled_imu_msg* n_var0, const
                               uint8_t* n_var1)
{
    uint32_t n_r0 = mavlink_unpack_uint32_t(n_var1, 0U);
    
    *&n_var0->time_boot_ms = n_r0;
    
    int16_t n_r1 = mavlink_unpack_int16_t(n_var1, 4U);
    
    *&n_var0->xacc = n_r1;
    
    int16_t n_r2 = mavlink_unpack_int16_t(n_var1, 6U);
    
    *&n_var0->yacc = n_r2;
    
    int16_t n_r3 = mavlink_unpack_int16_t(n_var1, 8U);
    
    *&n_var0->zacc = n_r3;
    
    int16_t n_r4 = mavlink_unpack_int16_t(n_var1, 10U);
    
    *&n_var0->xgyro = n_r4;
    
    int16_t n_r5 = mavlink_unpack_int16_t(n_var1, 12U);
    
    *&n_var0->ygyro = n_r5;
    
    int16_t n_r6 = mavlink_unpack_int16_t(n_var1, 14U);
    
    *&n_var0->zgyro = n_r6;
    
    int16_t n_r7 = mavlink_unpack_int16_t(n_var1, 16U);
    
    *&n_var0->xmag = n_r7;
    
    int16_t n_r8 = mavlink_unpack_int16_t(n_var1, 18U);
    
    *&n_var0->ymag = n_r8;
    
    int16_t n_r9 = mavlink_unpack_int16_t(n_var1, 20U);
    
    *&n_var0->zmag = n_r9;
}