/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __MAVLINK_HIL_STATE_MSG_H__
#define __MAVLINK_HIL_STATE_MSG_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "mavlinkSendModule.h"
#include "mavlink_pack_ivory.h"
struct hil_state_msg {
    uint64_t time_usec;
    float roll;
    float pitch;
    float yaw;
    float rollspeed;
    float pitchspeed;
    float yawspeed;
    int32_t lat;
    int32_t lon;
    int32_t alt;
    int16_t vx;
    int16_t vy;
    int16_t vz;
    int16_t xacc;
    int16_t yacc;
    int16_t zacc;
} __attribute__((__packed__));
void mavlink_hil_state_msg_send(const struct hil_state_msg* n_var0,
                                uint8_t* n_var1, uint8_t n_var2[80U]);
void mavlink_hil_state_unpack(struct hil_state_msg* n_var0, const
                              uint8_t* n_var1);

#ifdef __cplusplus
}
#endif
#endif /* __MAVLINK_HIL_STATE_MSG_H__ */