/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "mavlink_sys_status_msg.h"

void mavlink_sys_status_msg_send(const struct sys_status_msg* n_var0,
                                 uint8_t* n_var1, uint8_t n_var2[80U])
{
    uint8_t n_local0[31U] = {};
    uint8_t* n_ref1 = n_local0;
    uint32_t n_deref2 = n_var0->onboard_control_sensors_present;
    
    mavlink_pack_uint32_t((uint8_t*) n_ref1, 0U, n_deref2);
    
    uint32_t n_deref3 = n_var0->onboard_control_sensors_enabled;
    
    mavlink_pack_uint32_t((uint8_t*) n_ref1, 4U, n_deref3);
    
    uint32_t n_deref4 = n_var0->onboard_control_sensors_health;
    
    mavlink_pack_uint32_t((uint8_t*) n_ref1, 8U, n_deref4);
    
    uint16_t n_deref5 = n_var0->load;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 12U, n_deref5);
    
    uint16_t n_deref6 = n_var0->voltage_battery;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 14U, n_deref6);
    
    int16_t n_deref7 = n_var0->current_battery;
    
    mavlink_pack_int16_t((uint8_t*) n_ref1, 16U, n_deref7);
    
    uint16_t n_deref8 = n_var0->drop_rate_comm;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 18U, n_deref8);
    
    uint16_t n_deref9 = n_var0->errors_comm;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 20U, n_deref9);
    
    uint16_t n_deref10 = n_var0->errors_count1;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 22U, n_deref10);
    
    uint16_t n_deref11 = n_var0->errors_count2;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 24U, n_deref11);
    
    uint16_t n_deref12 = n_var0->errors_count3;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 26U, n_deref12);
    
    uint16_t n_deref13 = n_var0->errors_count4;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 28U, n_deref13);
    
    int8_t n_deref14 = n_var0->battery_remaining;
    
    mavlink_pack_int8_t((uint8_t*) n_ref1, 30U, n_deref14);
    for (int32_t n_ix15 = 0; n_ix15 <= 30; n_ix15++) {
        ASSERTS(n_ix15 > 0 && 2147483647 - n_ix15 >= 6 || n_ix15 <= 0);
        if (n_ix15 + 6 >= 80) { } else {
            uint8_t n_deref16 = n_ref1[n_ix15];
            
            ASSERTS(n_ix15 > 0 && 2147483641 >= n_ix15 || n_ix15 <= 0);
            ASSERTS(0 <= 6 + n_ix15 && 6 + n_ix15 < 80);
            *&n_var2[(6 + n_ix15) % 80] = n_deref16;
        }
    }
    mavlinkSendWithWriter(1U, 124U, 31U, n_var1, n_var2);
    for (int32_t n_ix17 = 0; n_ix17 <= 40; n_ix17++) {
        ASSERTS(n_ix17 > 0 && 2147483647 - n_ix17 >= 39 || n_ix17 <= 0);
        ASSERTS(0 <= n_ix17 + 39 && n_ix17 + 39 < 80);
        *&n_var2[(n_ix17 + 39) % 80] = 0U;
    }
    return;
}

void mavlink_sys_status_unpack(struct sys_status_msg* n_var0, const
                               uint8_t* n_var1)
{
    uint32_t n_r0 = mavlink_unpack_uint32_t(n_var1, 0U);
    
    *&n_var0->onboard_control_sensors_present = n_r0;
    
    uint32_t n_r1 = mavlink_unpack_uint32_t(n_var1, 4U);
    
    *&n_var0->onboard_control_sensors_enabled = n_r1;
    
    uint32_t n_r2 = mavlink_unpack_uint32_t(n_var1, 8U);
    
    *&n_var0->onboard_control_sensors_health = n_r2;
    
    uint16_t n_r3 = mavlink_unpack_uint16_t(n_var1, 12U);
    
    *&n_var0->load = n_r3;
    
    uint16_t n_r4 = mavlink_unpack_uint16_t(n_var1, 14U);
    
    *&n_var0->voltage_battery = n_r4;
    
    int16_t n_r5 = mavlink_unpack_int16_t(n_var1, 16U);
    
    *&n_var0->current_battery = n_r5;
    
    uint16_t n_r6 = mavlink_unpack_uint16_t(n_var1, 18U);
    
    *&n_var0->drop_rate_comm = n_r6;
    
    uint16_t n_r7 = mavlink_unpack_uint16_t(n_var1, 20U);
    
    *&n_var0->errors_comm = n_r7;
    
    uint16_t n_r8 = mavlink_unpack_uint16_t(n_var1, 22U);
    
    *&n_var0->errors_count1 = n_r8;
    
    uint16_t n_r9 = mavlink_unpack_uint16_t(n_var1, 24U);
    
    *&n_var0->errors_count2 = n_r9;
    
    uint16_t n_r10 = mavlink_unpack_uint16_t(n_var1, 26U);
    
    *&n_var0->errors_count3 = n_r10;
    
    uint16_t n_r11 = mavlink_unpack_uint16_t(n_var1, 28U);
    
    *&n_var0->errors_count4 = n_r11;
    
    int8_t n_r12 = mavlink_unpack_int8_t(n_var1, 30U);
    
    *&n_var0->battery_remaining = n_r12;
}