/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __MAVLINK_AUTH_KEY_MSG_H__
#define __MAVLINK_AUTH_KEY_MSG_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "mavlinkSendModule.h"
#include "mavlink_pack_ivory.h"
struct auth_key_msg {
    uint8_t key[32U];
} __attribute__((__packed__));
void mavlink_auth_key_msg_send(const struct auth_key_msg* n_var0,
                               uint8_t* n_var1, uint8_t n_var2[80U]);
void mavlink_auth_key_unpack(struct auth_key_msg* n_var0, const
                             uint8_t* n_var1);

#ifdef __cplusplus
}
#endif
#endif /* __MAVLINK_AUTH_KEY_MSG_H__ */