/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __MAVLINK_HIGHRES_IMU_MSG_H__
#define __MAVLINK_HIGHRES_IMU_MSG_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "mavlinkSendModule.h"
#include "mavlink_pack_ivory.h"
struct highres_imu_msg {
    uint64_t time_usec;
    float xacc;
    float yacc;
    float zacc;
    float xgyro;
    float ygyro;
    float zgyro;
    float xmag;
    float ymag;
    float zmag;
    float abs_pressure;
    float diff_pressure;
    float pressure_alt;
    float temperature;
    uint16_t fields_updated;
} __attribute__((__packed__));
void mavlink_highres_imu_msg_send(const struct highres_imu_msg* n_var0,
                                  uint8_t* n_var1, uint8_t n_var2[80U]);
void mavlink_highres_imu_unpack(struct highres_imu_msg* n_var0, const
                                uint8_t* n_var1);

#ifdef __cplusplus
}
#endif
#endif /* __MAVLINK_HIGHRES_IMU_MSG_H__ */