/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "mavlink_manual_control_msg.h"

void mavlink_manual_control_msg_send(const struct manual_control_msg* n_var0,
                                     uint8_t* n_var1, uint8_t n_var2[80U])
{
    uint8_t n_local0[11U] = {};
    uint8_t* n_ref1 = n_local0;
    int16_t n_deref2 = n_var0->x;
    
    mavlink_pack_int16_t((uint8_t*) n_ref1, 0U, n_deref2);
    
    int16_t n_deref3 = n_var0->y;
    
    mavlink_pack_int16_t((uint8_t*) n_ref1, 2U, n_deref3);
    
    int16_t n_deref4 = n_var0->z;
    
    mavlink_pack_int16_t((uint8_t*) n_ref1, 4U, n_deref4);
    
    int16_t n_deref5 = n_var0->r;
    
    mavlink_pack_int16_t((uint8_t*) n_ref1, 6U, n_deref5);
    
    uint16_t n_deref6 = n_var0->buttons;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 8U, n_deref6);
    
    uint8_t n_deref7 = n_var0->target;
    
    mavlink_pack_uint8_t((uint8_t*) n_ref1, 10U, n_deref7);
    for (int32_t n_ix8 = 0; n_ix8 <= 10; n_ix8++) {
        ASSERTS(n_ix8 > 0 && 2147483647 - n_ix8 >= 6 || n_ix8 <= 0);
        if (n_ix8 + 6 >= 80) { } else {
            uint8_t n_deref9 = n_ref1[n_ix8];
            
            ASSERTS(n_ix8 > 0 && 2147483641 >= n_ix8 || n_ix8 <= 0);
            ASSERTS(0 <= 6 + n_ix8 && 6 + n_ix8 < 80);
            *&n_var2[(6 + n_ix8) % 80] = n_deref9;
        }
    }
    mavlinkSendWithWriter(69U, 243U, 11U, n_var1, n_var2);
    for (int32_t n_ix10 = 0; n_ix10 <= 60; n_ix10++) {
        ASSERTS(n_ix10 > 0 && 2147483647 - n_ix10 >= 19 || n_ix10 <= 0);
        ASSERTS(0 <= n_ix10 + 19 && n_ix10 + 19 < 80);
        *&n_var2[(n_ix10 + 19) % 80] = 0U;
    }
    return;
}

void mavlink_manual_control_unpack(struct manual_control_msg* n_var0, const
                                   uint8_t* n_var1)
{
    int16_t n_r0 = mavlink_unpack_int16_t(n_var1, 0U);
    
    *&n_var0->x = n_r0;
    
    int16_t n_r1 = mavlink_unpack_int16_t(n_var1, 2U);
    
    *&n_var0->y = n_r1;
    
    int16_t n_r2 = mavlink_unpack_int16_t(n_var1, 4U);
    
    *&n_var0->z = n_r2;
    
    int16_t n_r3 = mavlink_unpack_int16_t(n_var1, 6U);
    
    *&n_var0->r = n_r3;
    
    uint16_t n_r4 = mavlink_unpack_uint16_t(n_var1, 8U);
    
    *&n_var0->buttons = n_r4;
    
    uint8_t n_r5 = mavlink_unpack_uint8_t(n_var1, 10U);
    
    *&n_var0->target = n_r5;
}