/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "mavlink_mission_current_msg.h"

void mavlink_mission_current_msg_send(const struct mission_current_msg* n_var0,
                                      uint8_t* n_var1, uint8_t n_var2[80U])
{
    uint8_t n_local0[2U] = {};
    uint8_t* n_ref1 = n_local0;
    uint16_t n_deref2 = n_var0->mission_current_seq;
    
    mavlink_pack_uint16_t((uint8_t*) n_ref1, 0U, n_deref2);
    for (int32_t n_ix3 = 0; n_ix3 <= 1; n_ix3++) {
        ASSERTS(n_ix3 > 0 && 2147483647 - n_ix3 >= 6 || n_ix3 <= 0);
        if (n_ix3 + 6 >= 80) { } else {
            uint8_t n_deref4 = n_ref1[n_ix3];
            
            ASSERTS(n_ix3 > 0 && 2147483641 >= n_ix3 || n_ix3 <= 0);
            ASSERTS(0 <= 6 + n_ix3 && 6 + n_ix3 < 80);
            *&n_var2[(6 + n_ix3) % 80] = n_deref4;
        }
    }
    mavlinkSendWithWriter(42U, 28U, 2U, n_var1, n_var2);
    for (int32_t n_ix5 = 0; n_ix5 <= 69; n_ix5++) {
        ASSERTS(n_ix5 > 0 && 2147483647 - n_ix5 >= 10 || n_ix5 <= 0);
        ASSERTS(0 <= n_ix5 + 10 && n_ix5 + 10 < 80);
        *&n_var2[(n_ix5 + 10) % 80] = 0U;
    }
    return;
}

void mavlink_mission_current_unpack(struct mission_current_msg* n_var0, const
                                    uint8_t* n_var1)
{
    uint16_t n_r0 = mavlink_unpack_uint16_t(n_var1, 0U);
    
    *&n_var0->mission_current_seq = n_r0;
}