/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __PARAM_TOWER_H__
#define __PARAM_TOWER_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
struct ivory_string_ParamString {
    uint8_t ivory_string_ParamString_data[16U];
    int32_t ivory_string_ParamString_len;
} __attribute__((__packed__));
struct param_info {
    struct ivory_string_ParamString param_name;
    int32_t param_index;
    float param_value;
} __attribute__((__packed__));

#ifdef __cplusplus
}
#endif
#endif /* __PARAM_TOWER_H__ */