/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __SENSORS_TYPE_H__
#define __SENSORS_TYPE_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
struct sensors_result {
    bool valid;
    float roll;
    float pitch;
    float yaw;
    float omega_x;
    float omega_y;
    float omega_z;
    float baro_alt;
    float xacc;
    float yacc;
    float zacc;
    uint32_t time;
} __attribute__((__packed__));

#ifdef __cplusplus
}
#endif
#endif /* __SENSORS_TYPE_H__ */