/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "tower_task_usercode_stateProxy_236.h"

void eventhandler_stateProxy_236_chan216_243(const struct position* n_var0)
{
    write_stateProxy_236_dataport235_238(n_var0);
}