/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "tower_task_usercode_stateProxy_192.h"

void eventhandler_stateProxy_192_chan34_199(const struct motors* n_var0)
{
    write_stateProxy_192_dataport191_194(n_var0);
}