/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "tower_task_usercode_stateProxy_622.h"

void eventhandler_stateProxy_622_chan587_629(const struct radio_stat* n_var0)
{
    write_stateProxy_622_dataport621_624(n_var0);
}