/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "tower_task_loop_armedMux_73.h"

static bool chan11_evt_ready_83;

static uint8_t chan11_evt_ref_84;

static bool per50_evt_ready_87;

static uint32_t per50_evt_ref_88;

static bool chan11_evt_ready_83;

static uint8_t chan11_evt_ref_84;

static bool per50_evt_ready_87;

static uint32_t per50_evt_ref_88;

void read_armedMux_73_dataport40_75(uint16_t n_var0[8U])
{ }

void write_armedMux_73_dataport12_77(const uint8_t* n_var0)
{ }

bool receiveFromTask_armedMux_73_chan11_82(uint8_t* n_var0)
{
    return true;
}