/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "tower_signal_comm_uartISR_211.h"

bool receiveFromSig_uartISR_211_chan209_213(uint8_t* n_var0)
{
    return true;
}

bool emitFromSig_uartISR_211_chan210_215(const uint8_t* n_var0)
{
    return true;
}