/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "tower_signal_comm_uartISR_574.h"

bool receiveFromSig_uartISR_574_chan572_576(uint8_t* n_var0)
{
    return true;
}

bool emitFromSig_uartISR_574_chan573_578(const uint8_t* n_var0)
{
    return true;
}