/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "tower_task_loop_sensorsCaptureTask_244.h"

static bool chan216_evt_ready_250;

static struct position chan216_evt_ref_251;

static bool per1_evt_ready_255;

static uint32_t per1_evt_ref_256;

static bool chan257_evt_ready_262;

static uint32_t chan257_evt_ref_263;

static bool chan216_evt_ready_250;

static struct position chan216_evt_ref_251;

static bool per1_evt_ready_255;

static uint32_t per1_evt_ref_256;

static bool chan257_evt_ready_262;

static uint32_t chan257_evt_ref_263;

bool emitFromTask_sensorsCaptureTask_244_chan0_246(const
                                                   struct sensors_result* n_var0)
{
    return true;
}

bool receiveFromTask_sensorsCaptureTask_244_chan216_249(struct position* n_var0)
{
    return true;
}

bool emitFromTask_sensorsCaptureTask_244_chan257_259(const uint32_t* n_var0)
{
    return true;
}

bool receiveFromTask_sensorsCaptureTask_244_chan257_261(uint32_t* n_var0)
{
    return true;
}