/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "tower_task_loop_userPPMInput_42.h"

static bool per50_evt_ready_53;

static uint32_t per50_evt_ref_54;

static bool per50_evt_ready_53;

static uint32_t per50_evt_ref_54;

void write_userPPMInput_42_dataport39_44(const struct flightmode* n_var0)
{ }

void write_userPPMInput_42_dataport36_46(const struct userinput_result* n_var0)
{ }

void write_userPPMInput_42_dataport40_48(const uint16_t n_var0[8U])
{ }