/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __TOWER_SIGNAL_USERCODE_UARTISR_211_H__
#define __TOWER_SIGNAL_USERCODE_UARTISR_211_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory_hw_prim.h>
#include "controloutput_type.h"
#include "data_rate.h"
#include "flightmode_type.h"
#include "gcsstream_timing.h"
#include "gps_type.h"
#include "ivory.h"
#include "mavlink_hil_state_msg.h"
#include "motors_type.h"
#include "optflow_type.h"
#include "radio_info_type.h"
#include "radio_stat_type.h"
#include "sensors_type.h"
#include "tower_primitives.h"
#include "tower_signal_comm_uartISR_211.h"
#include "userinput_type.h"
void nodeInit_uartISR_211();
void USART6_IRQHandler();

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_SIGNAL_USERCODE_UARTISR_211_H__ */