/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "tower_task_loop_blink_109.h"

static bool per125_evt_ready_118;

static uint32_t per125_evt_ref_119;

static bool per125_evt_ready_118;

static uint32_t per125_evt_ref_119;

void read_blink_109_dataport12_111(uint8_t* n_var0)
{ }

void read_blink_109_dataport10_113(struct flightmode* n_var0)
{ }