/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __TOWER_TASK_LOOP_DATALINK_589_H__
#define __TOWER_TASK_LOOP_DATALINK_589_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "controloutput_type.h"
#include "data_rate.h"
#include "flightmode_type.h"
#include "gcsstream_timing.h"
#include "gps_type.h"
#include "ivory.h"
#include "mavlink_hil_state_msg.h"
#include "motors_type.h"
#include "optflow_type.h"
#include "radio_info_type.h"
#include "radio_stat_type.h"
#include "sensors_type.h"
#include "tower_primitives.h"
#include "tower_task_usercode_datalink_589.h"
#include "userinput_type.h"
bool receiveFromTask_datalink_589_chan573_591(uint8_t* n_var0);
bool emitFromTask_datalink_589_chan586_595(const uint8_t n_var0[96U]);
bool emitFromTask_datalink_589_chan587_597(const struct radio_stat* n_var0);
bool emitFromTask_datalink_589_chan588_599(const struct radio_info* n_var0);
bool emitFromTask_datalink_589_chan572_611(const uint8_t* n_var0);
bool receiveFromTask_datalink_589_chan585_613(uint8_t n_var0[96U]);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_TASK_LOOP_DATALINK_589_H__ */