/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "tower_task_loop_decryptTask_uart5_630.h"

static bool chan586_evt_ready_635;

static uint8_t chan586_evt_ref_636[96U];

static bool chan586_evt_ready_635;

static uint8_t chan586_evt_ref_636[96U];

bool emitFromTask_decryptTask_uart5_630_chan580_632(const uint8_t n_var0[80U])
{
    return true;
}

bool receiveFromTask_decryptTask_uart5_630_chan586_634(uint8_t n_var0[96U])
{
    return true;
}