/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __TOWER_TASK_USERCODE_DATALINK_589_H__
#define __TOWER_TASK_USERCODE_DATALINK_589_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory_hw_prim.h>
#include "controloutput_type.h"
#include "data_rate.h"
#include "flightmode_type.h"
#include "gcsstream_timing.h"
#include "gps_type.h"
#include "hxstream_state_module.h"
#include "ivory.h"
#include "mavlink_hil_state_msg.h"
#include "motors_type.h"
#include "optflow_type.h"
#include "radio_info_type.h"
#include "radio_stat_type.h"
#include "sensors_type.h"
#include "tower_primitives.h"
#include "tower_task_loop_datalink_589.h"
#include "userinput_type.h"
extern struct hxstream_state hx_decoder_state_600;
extern uint32_t airdata_frames_decoded_601;
extern uint8_t airdata_decoded_602[96U];
extern bool airdata_overrun_603;
extern uint32_t rs_success_604;
extern uint32_t rs_fail_605;
extern uint8_t rs_msgtype_606;
extern int32_t rs_len_607;
extern uint8_t rs_buf_608[48U];
void eventhandler_datalink_589_chan573_609(const uint8_t* n_var0);
void eventhandler_datalink_589_chan585_616(const uint8_t n_var0[96U]);
void eventhandler_datalink_589_per250_620(const uint32_t* n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_TASK_USERCODE_DATALINK_589_H__ */