/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "tower_task_usercode_stateProxy_369.h"

void eventhandler_stateProxy_369_chan334_376(const struct radio_stat* n_var0)
{
    write_stateProxy_369_dataport368_371(n_var0);
}