/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "tower_task_usercode_stateProxy_201.h"

void eventhandler_stateProxy_201_chan35_208(const struct controloutput* n_var0)
{
    write_stateProxy_201_dataport200_203(n_var0);
}