/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __TOWER_TASK_USERCODE_UBLOXGPS_217_H__
#define __TOWER_TASK_USERCODE_UBLOXGPS_217_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "controloutput_type.h"
#include "data_rate.h"
#include "flightmode_type.h"
#include "gcsstream_timing.h"
#include "gps_type.h"
#include "ivory.h"
#include "mavlink_hil_state_msg.h"
#include "motors_type.h"
#include "optflow_type.h"
#include "radio_info_type.h"
#include "radio_stat_type.h"
#include "sensors_type.h"
#include "tower_primitives.h"
#include "tower_task_loop_ubloxGPS_217.h"
#include "userinput_type.h"
extern uint32_t state_224;
extern uint8_t pktClass_225;
extern uint8_t pktId_226;
extern uint16_t pktLen_227;
extern uint16_t payOffs_228;
extern uint8_t payload_229[52U];
extern struct position position_230;
extern uint8_t decode_state_231;
extern uint8_t ck_a_232;
extern uint8_t ck_a_233;
void nodeInit_ubloxGPS_217();
void decode(uint8_t* n_var0, uint8_t n_var1, uint8_t n_var2,
            uint8_t n_var3[52U], uint16_t n_var4, struct position* n_var5);
void eventhandler_ubloxGPS_217_chan210_234(const uint8_t* n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_TASK_USERCODE_UBLOXGPS_217_H__ */