/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "tower_task_loop_gcsTransmitTask_uart5_751.h"

static bool chan581_evt_ready_818;

static struct gcsstream_timing chan581_evt_ref_819;

static bool per50_evt_ready_822;

static uint32_t per50_evt_ref_823;

static bool chan581_evt_ready_818;

static struct gcsstream_timing chan581_evt_ref_819;

static bool per50_evt_ready_822;

static uint32_t per50_evt_ref_823;

void read_gcsTransmitTask_uart5_751_dataport10_753(struct flightmode* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport1_755(struct sensors_result* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport235_757(struct position* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport200_759(struct controloutput* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport191_761(struct motors* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport621_763(struct radio_stat* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport12_765(uint8_t* n_var0)
{ }

bool emitFromTask_gcsTransmitTask_uart5_751_chan579_767(const
                                                        uint8_t n_var0[80U])
{
    return true;
}

bool receiveFromTask_gcsTransmitTask_uart5_751_chan583_771(int16_t* n_var0)
{
    return true;
}

void read_gcsTransmitTask_uart5_751_dataport14_773(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport15_775(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport16_777(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport17_779(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport18_781(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport19_783(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport20_785(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport21_787(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport22_789(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport23_791(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport24_793(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport25_795(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport26_797(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport27_799(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport28_801(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport29_803(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport30_805(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport31_807(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport32_809(float* n_var0)
{ }

void read_gcsTransmitTask_uart5_751_dataport33_811(float* n_var0)
{ }

bool receiveFromTask_gcsTransmitTask_uart5_751_chan581_817(struct gcsstream_timing* n_var0)
{
    return true;
}