/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#ifndef __TOWER_TASK_LOOP_GCSRECEIVETASK_UART5_638_H__
#define __TOWER_TASK_LOOP_GCSRECEIVETASK_UART5_638_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "controloutput_type.h"
#include "data_rate.h"
#include "flightmode_type.h"
#include "gcsstream_timing.h"
#include "gps_type.h"
#include "ivory.h"
#include "mavlink_hil_state_msg.h"
#include "motors_type.h"
#include "optflow_type.h"
#include "radio_info_type.h"
#include "radio_stat_type.h"
#include "sensors_type.h"
#include "tower_primitives.h"
#include "tower_task_usercode_gcsReceiveTask_uart5_638.h"
#include "userinput_type.h"
bool emitFromTask_gcsReceiveTask_uart5_638_chan584_640(const
                                                       struct hil_state_msg* n_var0);
void write_gcsReceiveTask_uart5_638_dataport10_642(const
                                                   struct flightmode* n_var0);
bool emitFromTask_gcsReceiveTask_uart5_638_chan11_644(const uint8_t* n_var0);
void write_gcsReceiveTask_uart5_638_dataport14_646(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport15_648(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport16_650(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport17_652(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport18_654(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport19_656(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport20_658(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport21_660(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport22_662(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport23_664(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport24_666(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport25_668(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport26_670(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport27_672(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport28_674(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport29_676(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport30_678(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport31_680(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport32_682(const float* n_var0);
void write_gcsReceiveTask_uart5_638_dataport33_684(const float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport14_686(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport15_688(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport16_690(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport17_692(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport18_694(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport19_696(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport20_698(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport21_700(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport22_702(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport23_704(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport24_706(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport25_708(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport26_710(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport27_712(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport28_714(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport29_716(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport30_718(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport31_720(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport32_722(float* n_var0);
void read_gcsReceiveTask_uart5_638_dataport33_724(float* n_var0);
bool emitFromTask_gcsReceiveTask_uart5_638_chan583_726(const int16_t* n_var0);
bool emitFromTask_gcsReceiveTask_uart5_638_chan13_728(const
                                                      struct rc_channels_override_msg* n_var0);
bool emitFromTask_gcsReceiveTask_uart5_638_chan581_732(const
                                                       struct gcsstream_timing* n_var0);
bool emitFromTask_gcsReceiveTask_uart5_638_chan582_734(const
                                                       struct data_rate_state* n_var0);
bool receiveFromTask_gcsReceiveTask_uart5_638_chan580_739(uint8_t n_var0[80U]);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_TASK_LOOP_GCSRECEIVETASK_UART5_638_H__ */