/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.0
 */
#include "tower_task_loop_datalink_336.h"

static bool chan320_evt_ready_339;

static uint8_t chan320_evt_ref_340;

static bool chan332_evt_ready_361;

static uint8_t chan332_evt_ref_362[96U];

static bool per250_evt_ready_365;

static uint32_t per250_evt_ref_366;

static bool chan320_evt_ready_339;

static uint8_t chan320_evt_ref_340;

static bool chan332_evt_ready_361;

static uint8_t chan332_evt_ref_362[96U];

static bool per250_evt_ready_365;

static uint32_t per250_evt_ref_366;

bool receiveFromTask_datalink_336_chan320_338(uint8_t* n_var0)
{
    return true;
}

bool emitFromTask_datalink_336_chan333_342(const uint8_t n_var0[96U])
{
    return true;
}

bool emitFromTask_datalink_336_chan334_344(const struct radio_stat* n_var0)
{
    return true;
}

bool emitFromTask_datalink_336_chan335_346(const struct radio_info* n_var0)
{
    return true;
}

bool emitFromTask_datalink_336_chan319_358(const uint8_t* n_var0)
{
    return true;
}

bool receiveFromTask_datalink_336_chan332_360(uint8_t n_var0[96U])
{
    return true;
}