/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __FROM_SMACCM_CAN_MONITOR_H__
#define __FROM_SMACCM_CAN_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "canDriverTypes.h"
#include "fragment_reassembly_monitor.h"
#include "ivory.h"
#include "ivory_serialize.h"
#include "smaccm_can_module.h"
void callback_from_smaccm_can_2(const struct SMACCM_DATA__CAN_Frame_i *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __FROM_SMACCM_CAN_MONITOR_H__ */