/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __OUTPUT_CAN_FRAMING_WRITE_SELF2SERVER_MONITOR_H__
#define __OUTPUT_CAN_FRAMING_WRITE_SELF2SERVER_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "canDriverTypes.h"
#include "ivory.h"
#include "ivory_serialize.h"
#include "smaccm_can_module.h"
void callback_output_CAN_Framing_write_self2server_2(const uint8_t n_var0[80U]);

#ifdef __cplusplus
}
#endif
#endif /* __OUTPUT_CAN_FRAMING_WRITE_SELF2SERVER_MONITOR_H__ */