/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __FRAMEBUFFER_MONITOR_H__
#define __FRAMEBUFFER_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "smaccm_UART_module.h"
#include "towerUartDeps.h"
#include "hxstream_state_module.h"
#include "ivory_serialize.h"
#include "commsecDecodeState_monitor.h"
extern int32_t frameBuffer_2_ringbuffer_insert;
extern int32_t frameBuffer_2_ringbuffer_remove;
extern uint8_t frameBuffer_2_ringbuffer_buf[4U][96U];
void callback_push(const uint8_t n_var0[96U]);
void callback_periodic_pop(const int64_t *n_var0);
bool frameBuffer_2_ringbuffer_push(const uint8_t n_var0[96U]);
bool frameBuffer_2_ringbuffer_pop(uint8_t n_var0[96U]);

#ifdef __cplusplus
}
#endif
#endif /* __FRAMEBUFFER_MONITOR_H__ */
