/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.4
 */
#ifndef __FROM_SMACCM_UART_MONITOR_H__
#define __FROM_SMACCM_UART_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "smaccm_UART_module.h"
#include "towerUartDeps.h"
#include "hxstream_state_module.h"
#include "ivory_serialize.h"
#include "to_hx_monitor.h"
void callback_from_smaccm_uart_2(const struct SMACCM_DATA__UART_Packet_i *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __FROM_SMACCM_UART_MONITOR_H__ */
