/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TO_HX_MONITOR_H__
#define __TO_HX_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "smaccm_UART_module.h"
#include "towerUartDeps.h"
#include "hxstream_state_module.h"
#include "ivory_serialize.h"
#include "frame_datalink_decode_monitor.h"
void callback_unpack(const struct ivory_string_UartPacket *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __TO_HX_MONITOR_H__ */
