/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __CAN_H__
#define __CAN_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <CAN_CAN_hw_intermon.h>
#include <CAN_Server_intermon.h>
#include <CAN_hw_CAN_intermon.h>
#include <Server_CAN_intermon.h>
#include "input_CAN_hw_CAN_get_can_message_monitor.h"
#include "input_CAN_hw_CAN_get_status_monitor.h"
#include "input_Server_CAN_get_pt_data_monitor.h"
#include "ivory.h"
void component_entry(void);
void component_init(void);

#ifdef __cplusplus
}
#endif
#endif /* __CAN_H__ */