/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "frame_datalink_decode_monitor.h"

struct hxstream_state hx_decoder = {.fstate =(uint8_t) 2U, .offset =(int32_t) 0, .tagSeen =false};

uint8_t buf[195U];

bool overrun;

void callback_decoder_serial_in(const uint8_t *n_var0)
{
    uint8_t n_deref0 = *n_var0;
    const uint8_t *n_cse0 = &hx_decoder.fstate;
    uint8_t n_deref1 = *n_cse0;
    int32_t n_deref2 = hx_decoder.offset;
    bool n_deref3 = hx_decoder.tagSeen;
    uint8_t n_r4 = decodeSM(&hx_decoder, n_deref0);
    uint8_t n_deref5 = *n_cse0;
    uint8_t n_deref6 = hx_decoder.ftag;
    bool n_cse4 = (bool) ((uint8_t) 2U == n_deref1);
    
    if ((bool) (n_cse4 && (bool) ((bool) (n_deref5 == (uint8_t) 1U) && n_deref3))) {
        if ((bool) (0 == n_deref6)) {
            bool n_deref7 = overrun;
            
            if ((bool) !n_deref7) {
                uint8_t n_local8[96U] = {};
                uint8_t *n_ref9 = n_local8;
                
                for (int32_t n_ix10 = (int32_t) 0; n_ix10 <= (int32_t) 95; n_ix10++) {
                    ivory_serialize_unpack_uint8_be((const uint8_t *) buf, (uint32_t) n_ix10, &n_ref9[n_ix10]);
                }
                callback_push(n_ref9);
            }
        }
    } else {
        if ((bool) (n_deref1 == (uint8_t) 1U)) {
            if ((bool) (0 == n_deref6)) {
                overrun = false;
                for (int32_t n_ix11 = (int32_t) 0; n_ix11 <= (int32_t) 194; n_ix11++) {
                    buf[n_ix11] = (uint8_t) 0U;
                }
            }
        } else {
            if ((bool) (n_cse4 || (bool) (n_deref1 == (uint8_t) 3U))) {
                if ((bool) (0 == n_deref6)) {
                    if ((bool) (n_deref2 < (int32_t) 195)) {
                        buf[n_deref2 % 195] = n_r4;
                    } else {
                        overrun = true;
                    }
                }
            }
        }
    }
}