/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __INPUT_SERVER_UART_OUT_GET_PT_DATA_MONITOR_H__
#define __INPUT_SERVER_UART_OUT_GET_PT_DATA_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stdint.h>
void callback_input_Server_UART_out_get_pt_data_handler(const uint8_t n_var0[80U]);

#ifdef __cplusplus
}
#endif
#endif /* __INPUT_SERVER_UART_OUT_GET_PT_DATA_MONITOR_H__ */
