/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __INPUT_CAMERA_VM_SERVER_GET_CAMERA_DATA_MONITOR_H__
#define __INPUT_CAMERA_VM_SERVER_GET_CAMERA_DATA_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stdint.h>
void callback_input_Camera_VM_Server_get_camera_data_handler(const struct camera_data *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __INPUT_CAMERA_VM_SERVER_GET_CAMERA_DATA_MONITOR_H__ */
