/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __INPUT_CAN_CAN_HW_GET_CAN_MESSAGE_MONITOR_H__
#define __INPUT_CAN_CAN_HW_GET_CAN_MESSAGE_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stdint.h>
void callback_input_CAN_CAN_hw_get_can_message_handler(const struct can_message *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __INPUT_CAN_CAN_HW_GET_CAN_MESSAGE_MONITOR_H__ */
