/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __INPUT_CAN_HW_CAN_GET_CAN_MESSAGE_MONITOR_H__
#define __INPUT_CAN_HW_CAN_GET_CAN_MESSAGE_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
void callback_input_CAN_hw_CAN_get_can_message_handler(const struct can_message *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __INPUT_CAN_HW_CAN_GET_CAN_MESSAGE_MONITOR_H__ */
