/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __INPUT_CAN_HW_CAN_GET_STATUS_MONITOR_H__
#define __INPUT_CAN_HW_CAN_GET_STATUS_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stdint.h>
void callback_input_CAN_hw_CAN_get_status_handler(const bool *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __INPUT_CAN_HW_CAN_GET_STATUS_MONITOR_H__ */
