/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __INPUT_UART_HW_UART_OUT_GET_BOOL_MONITOR_H__
#define __INPUT_UART_HW_UART_OUT_GET_BOOL_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
void callback_input_UART_hw_UART_out_get_bool_handler(const bool *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __INPUT_UART_HW_UART_OUT_GET_BOOL_MONITOR_H__ */
