/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "ivory_serialize.h"

void ibool_get_le(const uint8_t *n_var0, uint32_t n_var1, bool *n_var2)
{
    uint8_t n_local0 = (uint8_t) 0U;
    uint8_t *n_ref1 = &n_local0;
    
    ivory_serialize_unpack_uint8_le(n_var0, n_var1, n_ref1);
    
    uint8_t n_deref2 = *n_ref1;
    
    *n_var2 = (bool) (0 != n_deref2);
}

void ibool_get_be(const uint8_t *n_var0, uint32_t n_var1, bool *n_var2)
{
    uint8_t n_local0 = (uint8_t) 0U;
    uint8_t *n_ref1 = &n_local0;
    
    ivory_serialize_unpack_uint8_be(n_var0, n_var1, n_ref1);
    
    uint8_t n_deref2 = *n_ref1;
    
    *n_var2 = (bool) (0 != n_deref2);
}

void ibool_set_le(uint8_t *n_var0, uint32_t n_var1, const bool *n_var2)
{
    uint8_t n_local0 = (uint8_t) 0U;
    uint8_t *n_ref1 = &n_local0;
    bool n_deref2 = *n_var2;
    
    *n_ref1 = (uint8_t) (n_deref2 ? (uint8_t) 1U : 0);
    ivory_serialize_pack_uint8_le(n_var0, n_var1, n_ref1);
}

void ibool_set_be(uint8_t *n_var0, uint32_t n_var1, const bool *n_var2)
{
    uint8_t n_local0 = (uint8_t) 0U;
    uint8_t *n_ref1 = &n_local0;
    bool n_deref2 = *n_var2;
    
    *n_ref1 = (uint8_t) (n_deref2 ? (uint8_t) 1U : 0);
    ivory_serialize_pack_uint8_be(n_var0, n_var1, n_ref1);
}