/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "output_CAN_CAN_hw_put_abort_monitor.h"
#include "smaccm_CAN_framing.h"

void callback_output_CAN_CAN_hw_put_abort_2(const bool *n_var0)
{
    //CAN_CAN_hw_put_abort(n_var0);
}
