/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "output_CAN_hw_CAN_put_can_message_monitor.h"

void callback_output_CAN_hw_CAN_put_can_message_2(const struct can_message *n_var0)
{
    CAN_hw_CAN_put_can_message(n_var0);
}