/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __OUTPUT_CAN_HW_CAN_PUT_STATUS_MONITOR_H__
#define __OUTPUT_CAN_HW_CAN_PUT_STATUS_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
void callback_output_CAN_hw_CAN_put_status_2(const bool *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __OUTPUT_CAN_HW_CAN_PUT_STATUS_MONITOR_H__ */
