/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __OUTPUT_UART_HW_UART_OUT_PUT_BOOL_MONITOR_H__
#define __OUTPUT_UART_HW_UART_OUT_PUT_BOOL_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif

void callback_output_UART_hw_UART_out_put_bool_2(const bool *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __OUTPUT_UART_HW_UART_OUT_PUT_BOOL_MONITOR_H__ */
