/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "rgb_led_setting_types.h"

void rgb_led_setting_get_le(const uint8_t *n_var0, uint32_t n_var1, struct rgb_led_setting *n_var2)
{
    ivory_serialize_unpack_uint8_le(n_var0, n_var1, &n_var2->red);
    ivory_serialize_unpack_uint8_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 1U), &n_var2->green);
    ivory_serialize_unpack_uint8_le(n_var0, (uint32_t) ((uint32_t) 2U + n_var1), &n_var2->blue);
}

void rgb_led_setting_get_be(const uint8_t *n_var0, uint32_t n_var1, struct rgb_led_setting *n_var2)
{
    ivory_serialize_unpack_uint8_be(n_var0, n_var1, &n_var2->red);
    ivory_serialize_unpack_uint8_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 1U), &n_var2->green);
    ivory_serialize_unpack_uint8_be(n_var0, (uint32_t) ((uint32_t) 2U + n_var1), &n_var2->blue);
}

void rgb_led_setting_set_le(uint8_t *n_var0, uint32_t n_var1, const struct rgb_led_setting *n_var2)
{
    ivory_serialize_pack_uint8_le(n_var0, n_var1, &n_var2->red);
    ivory_serialize_pack_uint8_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 1U), &n_var2->green);
    ivory_serialize_pack_uint8_le(n_var0, (uint32_t) ((uint32_t) 2U + n_var1), &n_var2->blue);
}

void rgb_led_setting_set_be(uint8_t *n_var0, uint32_t n_var1, const struct rgb_led_setting *n_var2)
{
    ivory_serialize_pack_uint8_be(n_var0, n_var1, &n_var2->red);
    ivory_serialize_pack_uint8_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 1U), &n_var2->green);
    ivory_serialize_pack_uint8_be(n_var0, (uint32_t) ((uint32_t) 2U + n_var1), &n_var2->blue);
}