/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "send_transdata_monitor.h"

void callback_send_translate(const struct ivory_string_HXCyphertext *n_var0)
{
    struct ivory_string_UartPacket n_local0 = {};
    struct ivory_string_UartPacket *n_ref1 = &n_local0;
    int32_t n_deref2 = n_var0->ivory_string_HXCyphertext_len;
    bool n_cse3 = (bool) ((bool) (n_deref2 >= (int32_t) 0) && (bool) (n_deref2 <= (int32_t) 195));
    
    ASSERTS(n_cse3);
    ASSERTS(n_cse3);
    for (int32_t n_ix3 = (int32_t) 0; n_ix3 <= (int32_t) 194; n_ix3++) {
        if ((bool) (n_ix3 < n_deref2)) {
            if ((bool) (n_ix3 < (int32_t) 255)) {
                uint8_t n_deref4 = n_var0->ivory_string_HXCyphertext_data[n_ix3];
                
                n_ref1->ivory_string_UartPacket_data[n_ix3 % 255] = n_deref4;
            }
        }
    }
    n_ref1->ivory_string_UartPacket_len = n_deref2;
    callback_send(n_ref1);
}