/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __STAB_CONFIG_TYPES_H__
#define __STAB_CONFIG_TYPES_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "ivory_serialize.h"
#include "pid_config_types.h"
typedef struct stab_config { struct pid_config pos;
                             struct pid_config rate;
} stab_config;
void stab_config_get_le(const uint8_t *n_var0, uint32_t n_var1, struct stab_config *n_var2);
void stab_config_get_be(const uint8_t *n_var0, uint32_t n_var1, struct stab_config *n_var2);
void stab_config_set_le(uint8_t *n_var0, uint32_t n_var1, const struct stab_config *n_var2);
void stab_config_set_be(uint8_t *n_var0, uint32_t n_var1, const struct stab_config *n_var2);

#ifdef __cplusplus
}
#endif
#endif /* __STAB_CONFIG_TYPES_H__ */