/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __UART_MONITOR_H__
#define __UART_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif

void callback_send(const struct ivory_string_UartPacket *n_var0);
void callback_recv_rx(const struct ivory_string_UartPacket *n_var0);
void callback_recv_resp(const bool *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __UART_MONITOR_H__ */
