/**************************************************************************
  Copyright (c) 2013, 2014, 2015 Rockwell Collins and the University of Minnesota.
  Developed with the sponsorship of the Defense Advanced Research Projects Agency (DARPA).

  Permission is hereby granted, free of charge, to any person obtaining a copy of this data,
  including any software or models in source or binary form, as well as any drawings, specifications, 
  and documentation (collectively "the Data"), to deal in the Data without restriction, including 
  without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
  and/or sell copies of the Data, and to permit persons to whom the Data is furnished to do so, 
  subject to the following conditions: 

  The above copyright notice and this permission notice shall be included in all copies or
  substantial portions of the Data.

  THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
  LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
  IN NO EVENT SHALL THE AUTHORS, SPONSORS, DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE LIABLE 
  FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE DATA. 

 **************************************************************************/


/**************************************************************************

   File: /home/ajgacek/smaccm/models/Trusted_Build_Test/camera_vm/components/receiver/src/smaccm_receiver.c
   Created on: 2015/06/10 10:30:46
   using Dulcimer AADL system build tool suite 

   ***AUTOGENERATED CODE: DO NOT MODIFY***

  This C file contains the implementations of the AADL primitives
  used by user-level declarations for thread receiver.   

  The user code runs in terms of "dispatchers", which cause 
  dispatch user-level handlers to execute.  These handlers can 
  communicate using the standard AADL primitives, which are mapped
  to C functions.

  The send/receive handlers are not thread safe in CAmkES; it is 
  assumed that this is handled by the CAmkES sequentialized access 
  to the dispatch handler.  There is only one dispatch interface 
  for the component containing all of the dispatch points.

  They are thread safe for eChronos.

  The read/write handlers are thread safe because the writer comes 
  through a dispatch interface but the reader is "local" on a dispatch
  interface and so contention may occur.


 **************************************************************************/


#include <string.h>
#include <smaccm_receiver.h>
#include <receiver.h>

///////////////////////////////////////////////////////////////////////////
//
// Local prototypes for AADL dispatchers
//
///////////////////////////////////////////////////////////////////////////
void 
smaccm_receiver_bbox_in_dispatcher(camera_vm__bbox_i * bbox_in); 
 
 



/************************************************************************
 * 
 * Static variables and queue management functions for port:
 * 	bbox_in
 * 
 ************************************************************************/

camera_vm__bbox_i smaccm_queue_bbox_in [1];
bool smaccm_queue_full_bbox_in  = false;
uint32_t smaccm_queue_front_bbox_in  = 0;
uint32_t smaccm_queue_back_bbox_in  = 0;

bool smaccm_queue_is_full_bbox_in() {
	return (smaccm_queue_front_bbox_in == smaccm_queue_back_bbox_in) && (smaccm_queue_full_bbox_in);
}

bool smaccm_queue_is_empty_bbox_in() {
	return (smaccm_queue_front_bbox_in == smaccm_queue_back_bbox_in) && (!smaccm_queue_full_bbox_in); 
}

bool smaccm_queue_read_bbox_in(camera_vm__bbox_i * bbox_in) {
	if (smaccm_queue_is_empty_bbox_in()) {
		return false;
	} else {
		memcpy(bbox_in, &smaccm_queue_bbox_in[smaccm_queue_back_bbox_in], sizeof(camera_vm__bbox_i));

		smaccm_queue_back_bbox_in = (smaccm_queue_back_bbox_in + 1) % 1; 
		smaccm_queue_full_bbox_in = false ; 
		return true;
	}
}

bool smaccm_queue_write_bbox_in(const camera_vm__bbox_i * bbox_in) {
	if (smaccm_queue_is_full_bbox_in()) {
		return false;
	} else {
		memcpy(&smaccm_queue_bbox_in[smaccm_queue_front_bbox_in], bbox_in, sizeof(camera_vm__bbox_i));

		smaccm_queue_front_bbox_in = (smaccm_queue_front_bbox_in + 1) % 1; 		
		if (smaccm_queue_back_bbox_in == smaccm_queue_front_bbox_in) { 
			smaccm_queue_full_bbox_in = true ; 
		}
		return true;
	}
}

/************************************************************************
 *  bbox_in_write_camera_vm__bbox_i: 
 * Invoked by: remote interface.
 * 
 * This is the function invoked by a remote RPC to write to an active-thread
 * input event data port.  It queues the input message into a circular buffer.
 * 
 ************************************************************************/

bool bbox_in_write_camera_vm__bbox_i(const camera_vm__bbox_i * arg) {
	bool result;
	smaccm_receiver_bbox_in_mut_lock(); 
	result = smaccm_queue_write_bbox_in( arg);
	smaccm_receiver_bbox_in_mut_unlock(); 
	smaccm_dispatch_sem_post();

	return result;
}


/************************************************************************
 *  receiver_read_bbox_in: 
 * Invoked from local active thread.
 * 
 * This is the function invoked by the active thread to read from the 
 * input event data queue circular buffer.
 * 
 ************************************************************************/

bool receiver_read_bbox_in(camera_vm__bbox_i * arg) {
	bool result; 
	smaccm_receiver_bbox_in_mut_lock(); 
	result = smaccm_queue_read_bbox_in(arg);
	smaccm_receiver_bbox_in_mut_unlock(); 
	return result;
}




 

/************************************************************************
 *  dispatch_dispatch_bbox_in: 
 * Invoked by remote RPC (or, for active thread, local dispatcher).
 * 
 * This is the function invoked by an active thread dispatcher to 
 * call to a user-defined entrypoint function.  It sets up the dispatch
 * context for the user-defined entrypoint, then calls it.
 * 
 ************************************************************************/

void dispatch_dispatch_bbox_in(
  const camera_vm__bbox_i * in_arg ,
  smaccm_receiver_bbox_in_struct *out_arg) {
	receive( in_arg); 

}	



/************************************************************************
 * 
smaccm_receiver_bbox_in_dispatcher
 * Invoked from local active thread.
 * 
 * This is the dispatcher function invoked to respond to an incoming thread 
 * stimulus: an ISR, a periodic dispatch, or a queued event.
 * 
 ******************************************************************************/
smaccm_receiver_bbox_in_struct smaccm_receiver_bbox_in_arg;

void 
smaccm_receiver_bbox_in_dispatcher(camera_vm__bbox_i * bbox_in) {

	 
	// make the call: 
	dispatch_dispatch_bbox_in( bbox_in,
  &smaccm_receiver_bbox_in_arg	
		); 
	 

}

 
/************************************************************************
 * run()
 * Main active thread function.
 * 
 ************************************************************************/

int run() {
	// port initialization routines (if any)... 

	// thread initialization routines (if any)...
	// register interrupt handlers (if any)...
	 

	// initial lock to await dispatch input.
	smaccm_dispatch_sem_wait();

	for(;;) {
		smaccm_dispatch_sem_wait();


		// drain the queues 
		while (!smaccm_queue_is_empty_bbox_in()) {
			camera_vm__bbox_i bbox_in ;
			smaccm_queue_read_bbox_in(&bbox_in);

			smaccm_receiver_bbox_in_dispatcher(&bbox_in); 
		}


	}
	// won't ever get here, but form must be followed
	return 0;
}



/**************************************************************************
  End of autogenerated file: /home/ajgacek/smaccm/models/Trusted_Build_Test/camera_vm/components/receiver/src/smaccm_receiver.c
 **************************************************************************/
