/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __LIDARLITE_SAMPLE_TYPES_H__
#define __LIDARLITE_SAMPLE_TYPES_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "ivory_serialize.h"
#include "time_micros_types.h"
typedef struct lidarlite_sample {
            bool samplefail;
            float distance;
            int64_t time;
        } lidarlite_sample;
void lidarlite_sample_get_le(const uint8_t *n_var0, uint32_t n_var1, struct lidarlite_sample *n_var2);
void lidarlite_sample_get_be(const uint8_t *n_var0, uint32_t n_var1, struct lidarlite_sample *n_var2);
void lidarlite_sample_set_le(uint8_t *n_var0, uint32_t n_var1, const struct lidarlite_sample *n_var2);
void lidarlite_sample_set_be(uint8_t *n_var0, uint32_t n_var1, const struct lidarlite_sample *n_var2);

#ifdef __cplusplus
}
#endif
#endif /* __LIDARLITE_SAMPLE_TYPES_H__ */
