/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __PX4FLOW_SAMPLE_TYPES_H__
#define __PX4FLOW_SAMPLE_TYPES_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "ivory_serialize.h"
#include "time_micros_types.h"
typedef struct px4flow_sample {
            uint16_t frame_count;
            int16_t pixel_flow_x_sum;
            int16_t pixel_flow_y_sum;
            int16_t flow_comp_m_x;
            int16_t flow_comp_m_y;
            int16_t quality;
            int16_t gyro_x_rate;
            int16_t gyro_y_rate;
            int16_t gyro_z_rate;
            uint8_t gyro_range;
            uint8_t sonar_timestamp;
            int16_t ground_distance;
            bool samplefail;
            int64_t time;
        } px4flow_sample;
void px4flow_sample_get_le(const uint8_t *n_var0, uint32_t n_var1, struct px4flow_sample *n_var2);
void px4flow_sample_get_be(const uint8_t *n_var0, uint32_t n_var1, struct px4flow_sample *n_var2);
void px4flow_sample_set_le(uint8_t *n_var0, uint32_t n_var1, const struct px4flow_sample *n_var2);
void px4flow_sample_set_be(uint8_t *n_var0, uint32_t n_var1, const struct px4flow_sample *n_var2);

#ifdef __cplusplus
}
#endif
#endif /* __PX4FLOW_SAMPLE_TYPES_H__ */
