/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __QUATERNION_TYPES_H__
#define __QUATERNION_TYPES_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "ivory_serialize.h"
typedef struct quaternion {
            float quat_a;
            float quat_b;
            float quat_c;
            float quat_d;
        } quaternion;
void quaternion_get_le(const uint8_t *n_var0, uint32_t n_var1, struct quaternion *n_var2);
void quaternion_get_be(const uint8_t *n_var0, uint32_t n_var1, struct quaternion *n_var2);
void quaternion_set_le(uint8_t *n_var0, uint32_t n_var1, const struct quaternion *n_var2);
void quaternion_set_be(uint8_t *n_var0, uint32_t n_var1, const struct quaternion *n_var2);

#ifdef __cplusplus
}
#endif
#endif /* __QUATERNION_TYPES_H__ */
