/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __SERVER_H__
#define __SERVER_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "input_tb_decrypt2self_dequeue_monitor.h"
#include "input_tb_framing2self_dequeue_monitor.h"
#include "input_tb_vm2self_read_monitor.h"
#include <tb_Server.h>
void component_entry(const int64_t *n_var0);
void component_init(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __SERVER_H__ */
