/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __SMACCM_CAMERA_MODULE_H__
#define __SMACCM_CAMERA_MODULE_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "tb_smaccmcopter_types.h"

#ifdef __cplusplus
}
#endif
#endif /* __SMACCM_CAMERA_MODULE_H__ */
