#ifdef __SMACCM_top_level_impl_Instance_types__H
#define __SMACCM_top_level_impl_Instance_types__H

/**************************************************************************
  Copyright (c) 2013, 2014 Rockwell Collins and the University of Minnesota.
  Developed with the sponsorship of the Defense Advanced Research Projects Agency (DARPA).

  Permission is hereby granted, free of charge, to any person obtaining a copy of this data,
  including any software or models in source or binary form, as well as any drawings, specifications, 
  and documentation (collectively "the Data"), to deal in the Data without restriction, including 
  without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
  and/or sell copies of the Data, and to permit persons to whom the Data is furnished to do so, 
  subject to the following conditions: 

  The above copyright notice and this permission notice shall be included in all copies or
  substantial portions of the Data.

  THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
  LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
  IN NO EVENT SHALL THE AUTHORS, SPONSORS, DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE LIABLE 
  FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE DATA. 

 **************************************************************************/


/**************************************************************************

   File: C:\docs\git_smaccm\smaccm\models\Trusted_Build_Test\Toy_CAmkES_models\interfaces\smaccm_top_level_impl_Instance_types.h
   Created on: 2014/09/09 10:16:26
   using Dulcimer AADL system build tool suite 

   ***AUTOGENERATED CODE: DO NOT MODIFY***

  This file contains the datatypes used for communications between 
  AADL components as defined in the system implementation top_level_impl_Instance.

 **************************************************************************/
	typedef 
      struct { 
         float pos_rate_setp  ; 
         float ui_setp  ; 
         float thrust_i_reset  ; 
         float thrust_d  ; 
         float pos_p  ; 
         float ui_rate_setp  ; 
         float alt_rate_est  ; 
         float thrust_p  ; 
         float pos_i  ; 
         float alt_est  ; 
         float pos_setp  ; 
         float pos_d  ; 
         float thrust_i  ; 
      } Schedulability_Toy__alt_ctl_debug_msg_impl ; 

/**************************************************************************
  This header section contains the AADL gluecode interfaces used by the client
  for the thread implementations.
 **************************************************************************/
typedef 
  struct { 
     float pos_rate_setp  ; 
     float ui_setp  ; 
     float thrust_i_reset  ; 
     float thrust_d  ; 
     float pos_p  ; 
     float ui_rate_setp  ; 
     float alt_rate_est  ; 
     float thrust_p  ; 
     float pos_i  ; 
     float alt_est  ; 
     float pos_setp  ; 
     float pos_d  ; 
     float thrust_i  ; 
  } Schedulability_Toy__alt_ctl_debug_msg_impl ; 

typedef Schedulability_Toy__alt_ctl_debug_msg_impl smaccm_Schedulability_Toy__alt_ctl_debug_msg_impl_array_1 [1]; 

typedef uint32_t smaccm_uint32_t_array_2 [2]; 

typedef uint32_t smaccm_uint32_t_array_1 [1]; 

/* endif for: #ifdef __SMACCM_top_level_impl_Instance_types__H */
#endif

/**************************************************************************
  End of autogenerated file: smaccm_top_level_impl_Instance_types.h
 **************************************************************************/

