/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "px4io_alarms_types.h"

void px4io_alarms_get_le(const uint8_t *n_var0, uint32_t n_var1, struct px4io_alarms *n_var2)
{
    ibool_get_le(n_var0, n_var1, &n_var2->vservo_fault);
    ibool_get_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 1U), &n_var2->pwm_error);
    ibool_get_le(n_var0, (uint32_t) ((uint32_t) 2U + n_var1), &n_var2->rc_lost);
    ibool_get_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 3U), &n_var2->fmu_lost);
    ibool_get_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 4U), &n_var2->acc_current);
    ibool_get_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 5U), &n_var2->servo_current);
    ibool_get_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 6U), &n_var2->temperature);
    ibool_get_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 7U), &n_var2->vbatt_low);
}

void px4io_alarms_get_be(const uint8_t *n_var0, uint32_t n_var1, struct px4io_alarms *n_var2)
{
    ibool_get_be(n_var0, n_var1, &n_var2->vservo_fault);
    ibool_get_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 1U), &n_var2->pwm_error);
    ibool_get_be(n_var0, (uint32_t) ((uint32_t) 2U + n_var1), &n_var2->rc_lost);
    ibool_get_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 3U), &n_var2->fmu_lost);
    ibool_get_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 4U), &n_var2->acc_current);
    ibool_get_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 5U), &n_var2->servo_current);
    ibool_get_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 6U), &n_var2->temperature);
    ibool_get_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 7U), &n_var2->vbatt_low);
}

void px4io_alarms_set_le(uint8_t *n_var0, uint32_t n_var1, const struct px4io_alarms *n_var2)
{
    ibool_set_le(n_var0, n_var1, &n_var2->vservo_fault);
    ibool_set_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 1U), &n_var2->pwm_error);
    ibool_set_le(n_var0, (uint32_t) ((uint32_t) 2U + n_var1), &n_var2->rc_lost);
    ibool_set_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 3U), &n_var2->fmu_lost);
    ibool_set_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 4U), &n_var2->acc_current);
    ibool_set_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 5U), &n_var2->servo_current);
    ibool_set_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 6U), &n_var2->temperature);
    ibool_set_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 7U), &n_var2->vbatt_low);
}

void px4io_alarms_set_be(uint8_t *n_var0, uint32_t n_var1, const struct px4io_alarms *n_var2)
{
    ibool_set_be(n_var0, n_var1, &n_var2->vservo_fault);
    ibool_set_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 1U), &n_var2->pwm_error);
    ibool_set_be(n_var0, (uint32_t) ((uint32_t) 2U + n_var1), &n_var2->rc_lost);
    ibool_set_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 3U), &n_var2->fmu_lost);
    ibool_set_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 4U), &n_var2->acc_current);
    ibool_set_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 5U), &n_var2->servo_current);
    ibool_set_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 6U), &n_var2->temperature);
    ibool_set_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 7U), &n_var2->vbatt_low);
}