/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.4
 */
#include "from_smaccm_uart_monitor.h"

void callback_from_smaccm_uart_2(const struct SMACCM_DATA__UART_Packet_i *n_var0)
{
    int32_t n_deref0 = n_var0->buf_len;
    struct ivory_string_UartPacket n_local1 = {.ivory_string_UartPacket_len =n_deref0};
    struct ivory_string_UartPacket *n_ref2 = &n_local1;
    
    if (n_ref2->ivory_string_UartPacket_data != n_var0->buf)
        memcpy(n_ref2->ivory_string_UartPacket_data, n_var0->buf, sizeof(uint8_t [255U]));
    else
        COMPILER_ASSERTS(false);
    callback_unpack(n_ref2);
}
