/**************************************************************************
  Copyright (c) 2013-2016 Rockwell Collins and the University of
  Minnesota. Developed with the sponsorship of the Defense Advanced
  Research Projects Agency (DARPA).

  Permission is hereby granted, free of charge, to any person
  obtaining a copy of this data, including any software or models
  in source or binary form, as well as any drawings,
  specifications, and documentation (collectively "the Data"), to
  deal in the Data without restriction, including without
  limitation the rights to use, copy, modify, merge, publish,
  distribute, sublicense, and/or sell copies of the Data, and to
  permit persons to whom the Data is furnished to do so, subject to
  the following conditions:

  The above copyright notice and this permission notice shall be
  included in all copies or substantial portions of the Data.

  THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS, SPONSORS,
  DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
  CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
  CONNECTION WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE
  DATA.
 **************************************************************************/

/**************************************************************************

  ***AUTOGENERATED CODE: DO NOT MODIFY***

  This C file contains the implementations of the AADL primitives
  used by user-level declarations for thread Decrypt.

  The user code runs in terms of "dispatchers", which cause
  dispatch user-level handlers to execute.  These handlers can
  communicate using the standard AADL primitives, which are mapped
  to C functions.

  The send/receive handlers are not thread safe in CAmkES; it is
  assumed that this is handled by the CAmkES sequentialized access
  to the dispatch handler.  There is only one dispatch interface
  for the component containing all of the dispatch points.

  They are thread safe for eChronos.

  The read/write handlers are thread safe because the writer comes
  through a dispatch interface but the reader is "local" on a dispatch
  interface and so contention may occur.

 **************************************************************************/

#include "tb_Decrypt.h"
#include <string.h>
#include <camkes.h>

/************************************************************************
 * periodic_dispatcher Declarations
 *
 ************************************************************************/

static bool tb_occurred_periodic_dispatcher;
static int64_t tb_time_periodic_dispatcher;

/************************************************************************
 * periodic_dispatcher_write_int64_t
 * Invoked from remote periodic dispatch thread.
 *
 * This function records the current time and triggers the active thread
 * dispatch from a periodic event.  Note that the periodic dispatch
 * thread is the *only* thread that triggers a dispatch, so we do not
 * mutex lock the function.
 *
 ************************************************************************/

bool periodic_dispatcher_write_int64_t(const int64_t * arg) {
    tb_occurred_periodic_dispatcher = true;
    tb_time_periodic_dispatcher = *arg;
    tb_dispatch_sem_post();

    return true;
}
  /************************************************************************
 *
 * Static variables and queue management functions for event data port:
 *     uart2self
 *
 ************************************************************************/

static SMACCM_DATA__UART_Packet_i tb_queue_uart2self [1];
static bool tb_queue_full_uart2self  = false;
static uint32_t tb_queue_front_uart2self  = 0;
static uint32_t tb_queue_back_uart2self  = 0;

static bool tb_queue_is_full_uart2self() {
    return (tb_queue_front_uart2self == tb_queue_back_uart2self) && (tb_queue_full_uart2self);
}

static bool tb_queue_is_empty_uart2self() {
    return (tb_queue_front_uart2self == tb_queue_back_uart2self) && (!tb_queue_full_uart2self);
}

static bool tb_queue_read_uart2self(SMACCM_DATA__UART_Packet_i * uart2self) {
    if (tb_queue_is_empty_uart2self()) {
        return false;
    } else {
        memcpy(uart2self, &tb_queue_uart2self[tb_queue_front_uart2self], sizeof(SMACCM_DATA__UART_Packet_i));

        tb_queue_front_uart2self = (tb_queue_front_uart2self + 1) % 1;
        tb_queue_full_uart2self = false ;
        return true;
    }
}

static bool tb_queue_write_uart2self(const SMACCM_DATA__UART_Packet_i * uart2self) {
    if (tb_queue_is_full_uart2self()) {
        return false;
    } else {
        memcpy(&tb_queue_uart2self[tb_queue_back_uart2self], uart2self, sizeof(SMACCM_DATA__UART_Packet_i));

        tb_queue_back_uart2self = (tb_queue_back_uart2self + 1) % 1;
        if (tb_queue_back_uart2self == tb_queue_front_uart2self) {
            tb_queue_full_uart2self = true ;
        }
        return true;
    }
}

/************************************************************************
 *  uart2self_write_SMACCM_DATA__UART_Packet_i:
 * Invoked by: remote interface.
 *
 * This is the function invoked by a remote RPC to write to an active-thread
 * input event data port.  It queues the input message into a circular buffer.
 *
 ************************************************************************/

bool uart2self_write_SMACCM_DATA__UART_Packet_i(const SMACCM_DATA__UART_Packet_i * arg) {
    bool result;
    tb_decrypt_uart2self_mut_lock();
    result = tb_queue_write_uart2self( arg);
    tb_decrypt_uart2self_mut_unlock();
    return result;
}


/************************************************************************
 *  tb_Decrypt_read_uart2self:
 * Invoked from local active thread.
 *
 * This is the function invoked by the active thread to read from the
 * input event data queue circular buffer.
 *
 ************************************************************************/

bool tb_Decrypt_read_uart2self(SMACCM_DATA__UART_Packet_i * arg) {
    bool result;
    tb_decrypt_uart2self_mut_lock();
    result = tb_queue_read_uart2self(arg);
    tb_decrypt_uart2self_mut_unlock();
    return result;
}
 /************************************************************************
 *  tb_Decrypt_write_self2server:
 * Invoked from user code in the local thread.
 *
 * This is the function invoked by the local thread to make a
 * call to write to a remote data port.
 *
 ************************************************************************/

bool tb_Decrypt_write_self2server(const SMACCM_DATA__GIDL self2server) {
    bool tb_result = true ; 

    tb_result &= self2server_write_SMACCM_DATA__GIDL((tb_SMACCM_DATA__GIDL_container *) self2server);

    return tb_result;
} 


/************************************************************************
 *  tb_entrypoint_Decrypt_periodic_dispatcher:
 *
 * This is the function invoked by an active thread dispatcher to
 * call to a user-defined entrypoint function.  It sets up the dispatch
 * context for the user-defined entrypoint, then calls it.
 *
 ************************************************************************/
void tb_entrypoint_Decrypt_periodic_dispatcher(const int64_t * in_arg) {
    component_entry( in_arg);

}

/************************************************************************
 *  tb_entrypoint_Decrypt_Decrypt_initializer:
 *
 * This is the function invoked by an active thread dispatcher to
 * call to a user-defined entrypoint function.  It sets up the dispatch
 * context for the user-defined entrypoint, then calls it.
 *
 ************************************************************************/
void tb_entrypoint_Decrypt_Decrypt_initializer(const int64_t * in_arg) {
    component_init( in_arg);

}

/************************************************************************
 *  tb_entrypoint_Decrypt_uart2self:
 *
 * This is the function invoked by an active thread dispatcher to
 * call to a user-defined entrypoint function.  It sets up the dispatch
 * context for the user-defined entrypoint, then calls it.
 *
 ************************************************************************/
void tb_entrypoint_Decrypt_uart2self(const SMACCM_DATA__UART_Packet_i * in_arg) {
}


/************************************************************************
 * int run(void)
 * Main active thread function.
 *
 ************************************************************************/

int run(void) {
    {
    int64_t tb_dummy;
    tb_entrypoint_Decrypt_Decrypt_initializer(&tb_dummy);
    }
    // Initial lock to await dispatch input.
    tb_dispatch_sem_wait();

    for(;;) {
        tb_dispatch_sem_wait();


        // Drain the queues
        if (tb_occurred_periodic_dispatcher) {
            tb_occurred_periodic_dispatcher = false;
            tb_entrypoint_Decrypt_periodic_dispatcher(&tb_time_periodic_dispatcher);
        }
            
    }

    // Won't ever get here, but form must be followed
    return 0;
}

