/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "to_hx_monitor.h"

void callback_unpack(const struct SMACCM_DATA__UART_Packet_i *n_var0)
{
    int32_t n_deref0 = n_var0->buf_len;
    
    for (int32_t n_ix1 = (int32_t) 0; n_ix1 <= (int32_t) 254; n_ix1++) {
        if ((bool) (n_ix1 < n_deref0)) {
            callback_decoder_serial_in(&n_var0->buf[n_ix1]);
        }
    }
}
