<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="resolute" nsURI="http://www.rockwellcollins.com/atc/resolute/Resolute"
    nsPrefix="resolute">
  <eClassifiers xsi:type="ecore:EClass" name="ResoluteLibrary" eSuperTypes="../../../../../../org.osate.aadl2/model/aadl2.ecore#//AnnexLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" upperBound="-1"
        eType="#//Definition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Definition" eSuperTypes="../../../../../../org.osate.aadl2/model/aadl2.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="../../../../../../org.osate.aadl2/model/aadl2.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BuiltinType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Arg" eSuperTypes="../../../../../../org.osate.aadl2/model/aadl2.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantDefinition" eSuperTypes="#//Definition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDefinition" eSuperTypes="../../../../../../org.osate.aadl2/model/aadl2.ecore#//Namespace #//Definition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//Arg"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//DefinitionBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClaimString" eSuperTypes="../../../../../../org.osate.aadl2/model/aadl2.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefinitionBody" eSuperTypes="../../../../../../org.osate.aadl2/model/aadl2.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expr" eSuperTypes="../../../../../../org.osate.aadl2/model/aadl2.ecore#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResoluteSubclause" eSuperTypes="../../../../../../org.osate.aadl2/model/aadl2.ecore#//AnnexSubclause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="proves" upperBound="-1"
        eType="#//ProveStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProveStatement" eSuperTypes="../../../../../../org.osate.aadl2/model/aadl2.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClaimArg" eSuperTypes="#//ClaimString">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" eType="#//Arg"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuncBody" eSuperTypes="#//DefinitionBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClaimBody" eSuperTypes="#//DefinitionBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="claim" upperBound="-1"
        eType="#//ClaimString" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpr" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpr" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdExpr" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="ecore:EClass ../../../../../../org.osate.aadl2/model/aadl2.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThisExpr" eSuperTypes="#//Expr"/>
  <eClassifiers xsi:type="ecore:EClass" name="FailExpr" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="val" eType="ecore:EClass ../../../../../../org.osate.aadl2/model/aadl2.ecore#//StringLiteral"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntExpr" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="val" eType="ecore:EClass ../../../../../../org.osate.aadl2/model/aadl2.ecore#//IntegerLiteral"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealExpr" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="val" eType="ecore:EClass ../../../../../../org.osate.aadl2/model/aadl2.ecore#//RealLiteral"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolExpr" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="val" eType="ecore:EClass ../../../../../../org.osate.aadl2/model/aadl2.ecore#//BooleanLiteral"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringExpr" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="val" eType="ecore:EClass ../../../../../../org.osate.aadl2/model/aadl2.ecore#//StringLiteral"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfThenElseExpr" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cond" eType="#//Expr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//Expr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuantifiedExpr" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//Arg"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuiltInFuncCallExpr" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FnCallExpr" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fn" eType="#//FunctionDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilterMapExpr" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="map" eType="#//Expr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//Arg"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" eType="#//Expr"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
