/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __SEQUENCE_NUM_TYPES_H__
#define __SEQUENCE_NUM_TYPES_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "ivory_serialize.h"
void sequence_num_t_get_le(const uint8_t *n_var0, uint32_t n_var1, uint32_t *n_var2);
void sequence_num_t_get_be(const uint8_t *n_var0, uint32_t n_var1, uint32_t *n_var2);
void sequence_num_t_set_le(uint8_t *n_var0, uint32_t n_var1, const uint32_t *n_var2);
void sequence_num_t_set_be(uint8_t *n_var0, uint32_t n_var1, const uint32_t *n_var2);

#ifdef __cplusplus
}
#endif
#endif /* __SEQUENCE_NUM_TYPES_H__ */