/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __SEQUENCE_NUMBERED_BAROMETER_SAMPLE_TYPES_H__
#define __SEQUENCE_NUMBERED_BAROMETER_SAMPLE_TYPES_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "barometer_sample_types.h"
#include "ivory.h"
#include "ivory_serialize.h"
#include "sequence_num_types.h"
typedef struct sequence_numbered_barometer_sample { uint32_t seqnum;
                                                    struct barometer_sample val;
} sequence_numbered_barometer_sample;
void sequence_numbered_barometer_sample_get_le(const uint8_t *n_var0, uint32_t n_var1, struct sequence_numbered_barometer_sample *n_var2);
void sequence_numbered_barometer_sample_get_be(const uint8_t *n_var0, uint32_t n_var1, struct sequence_numbered_barometer_sample *n_var2);
void sequence_numbered_barometer_sample_set_le(uint8_t *n_var0, uint32_t n_var1, const struct sequence_numbered_barometer_sample *n_var2);
void sequence_numbered_barometer_sample_set_be(uint8_t *n_var0, uint32_t n_var1, const struct sequence_numbered_barometer_sample *n_var2);

#ifdef __cplusplus
}
#endif
#endif /* __SEQUENCE_NUMBERED_BAROMETER_SAMPLE_TYPES_H__ */