/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __TO_HX_MONITOR_H__
#define __TO_HX_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "towerUartDeps.h"
void callback_unpack(const struct ivory_string_UartPacket *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __TO_HX_MONITOR_H__ */
