#ifndef __SMACCM_sys_impl_Instance_types__H
#define __SMACCM_sys_impl_Instance_types__H

/**************************************************************************
  Copyright (c) 2013, 2014, 2015 Rockwell Collins and the University of Minnesota.
  Developed with the sponsorship of the Defense Advanced Research Projects Agency (DARPA).

  Permission is hereby granted, free of charge, to any person obtaining a copy of this data,
  including any software or models in source or binary form, as well as any drawings, specifications, 
  and documentation (collectively "the Data"), to deal in the Data without restriction, including 
  without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
  and/or sell copies of the Data, and to permit persons to whom the Data is furnished to do so, 
  subject to the following conditions: 

  The above copyright notice and this permission notice shall be included in all copies or
  substantial portions of the Data.

  THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
  LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
  IN NO EVENT SHALL THE AUTHORS, SPONSORS, DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE LIABLE 
  FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE DATA. 

 **************************************************************************/


/**************************************************************************

   File: /home/john/phase2/camkes/apps/smaccmpilot/./include/smaccm_sys_impl_types.h
   Created on: 2015/09/05 18:49:37
   using Dulcimer AADL system build tool suite 

   ***AUTOGENERATED CODE: DO NOT MODIFY***

  This file contains the datatypes used for communications between 
  AADL components as defined in the system implementation sys_impl_Instance.

 **************************************************************************/

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
// Headers for externally declared types.

#include "sequence_numbered_tristate_types.h" 

#include "sequence_numbered_stab_config_types.h" 

#include "sequence_numbered_quadcopter_motors_types.h" 

#include "sequence_numbered_throttle_ui_types.h" 

#include "sequence_numbered_accelerometer_sample_types.h" 

#include "sequence_numbered_att_control_debug_types.h" 

#include "sequence_numbered_sensors_result_types.h" 

#include "hx_cyphertext.h" 

#include "sequence_numbered_float_types.h" 

#include "sequence_numbered_reboot_types.h" 

#include "sequence_numbered_magnetometer_sample_types.h" 

#include "sequence_numbered_pid_config_types.h" 

#include "sequence_numbered_rc_input_types.h" 

#include "sequence_numbered_alt_control_debug_types.h" 

#include "sequence_numbered_user_input_types.h" 

#include "sequence_numbered_rgb_led_setting_types.h" 

#include "sequence_numbered_position_sample_types.h" 

#include "heartbeat_types.h" 

#include "sequence_numbered_xyz_calibration_types.h" 

#include "sequence_numbered_control_setpoint_types.h" 

#include "sequence_numbered_control_law_types.h" 

#include "sequence_numbered_packed_status_types.h" 

#include "sequence_numbered_control_modes_types.h" 

#include "sequence_numbered_gyroscope_sample_types.h" 

#include "sequence_numbered_arming_status_types.h" 

#include "towerCameraVMDeps.h" 

#include "canDriverTypes.h" 

#include "towerUartDeps.h" 

#include "sequence_numbered_user_input_result_types.h" 

#include "sequence_numbered_camera_target_types.h" 

#include "sequence_numbered_px4io_state_types.h" 

#include "sequence_numbered_barometer_sample_types.h" 

#include "sequence_numbered_control_output_types.h" 


// AADL-defined types.
typedef uint8_t Data_Types__array_80_Unsigned_8_impl [80]; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_yawRatePidSetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_yawRatePidSetReqConsumer_0_data [1] ; 
         uint32_t Output_yawRatePidSetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_yawRatePidSetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_yawPositionPidSetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_yawPositionPidSetRespProducer_0_data [1] ; 
         uint32_t Output_yawPositionPidSetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_yawPositionPidSetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_userInputRequestSetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_userInputRequestSetRespProducer_0_data [1] ; 
         uint32_t Output_userInputRequestSetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_userInputRequestSetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_altitudeRatePidGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_altitudeRatePidGetReqConsumer_0_data [1] ; 
         uint32_t Output_altitudeRatePidGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_altitudeRatePidGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_yawPositionPidSetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_yawPositionPidSetReqConsumer_0_data [1] ; 
         uint32_t Output_yawPositionPidSetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_yawPositionPidSetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_attitudePitchStabGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_attitudePitchStabGetRespProducer_0_data [1] ; 
         uint32_t Output_attitudePitchStabGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_attitudePitchStabGetRespProducer_struct ; 

typedef uint8_t Data_Types__array_96_Unsigned_8_impl [96]; 

typedef 
      struct smaccm_frameBuffer_Input_5ms_struct { 
         Data_Types__array_96_Unsigned_8_impl Output_periodic_pop_0_data [1] ; 
         uint32_t Output_periodic_pop_0_index  ; 
      } smaccm_frameBuffer_Input_5ms_struct ; 

typedef 
      struct smaccm_fragment_drop_Input_new_msg_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_new_msg_0_data [1] ; 
         uint32_t Output_new_msg_0_index  ; 
      } smaccm_fragment_drop_Input_new_msg_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_magOutputCalibrationGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_magOutputCalibrationGetReqConsumer_0_data [1] ; 
         uint32_t Output_magOutputCalibrationGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_magOutputCalibrationGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_accelRawOutputGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_accelRawOutputGetRespProducer_0_data [1] ; 
         uint32_t Output_accelRawOutputGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_accelRawOutputGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_magOutputCalibrationGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_magOutputCalibrationGetRespProducer_0_data [1] ; 
         uint32_t Output_magOutputCalibrationGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_magOutputCalibrationGetRespProducer_struct ; 

typedef 
      struct smaccm_periodic_camera_injector_Input_cameraDataRx_struct { 
         uint32_t unused  ; 
      } smaccm_periodic_camera_injector_Input_cameraDataRx_struct ; 

typedef 
      struct smaccm_commsecDecodeState_Input_gec_decode_init_struct { 
         uint32_t unused  ; 
      } smaccm_commsecDecodeState_Input_gec_decode_init_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_accelCalibrationGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_accelCalibrationGetRespProducer_0_data [1] ; 
         uint32_t Output_accelCalibrationGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_accelCalibrationGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerOutput_Input_parse_frame_struct { 
         sequence_numbered_magnetometer_sample Output_parse_frame_39_data [1] ; 
         uint32_t Output_parse_frame_39_index  ; 
         sequence_numbered_packed_status Output_parse_frame_25_data [1] ; 
         uint32_t Output_parse_frame_25_index  ; 
         uint32_t Output_parse_frame_1_data [1] ; 
         uint32_t Output_parse_frame_1_index  ; 
         uint32_t Output_parse_frame_3_data [1] ; 
         uint32_t Output_parse_frame_3_index  ; 
         uint32_t Output_parse_frame_5_data [1] ; 
         uint32_t Output_parse_frame_5_index  ; 
         uint32_t Output_parse_frame_7_data [1] ; 
         uint32_t Output_parse_frame_7_index  ; 
         uint32_t Output_parse_frame_9_data [1] ; 
         uint32_t Output_parse_frame_9_index  ; 
         sequence_numbered_float Output_parse_frame_51_data [1] ; 
         uint32_t Output_parse_frame_51_index  ; 
         sequence_numbered_pid_config Output_parse_frame_12_data [1] ; 
         uint32_t Output_parse_frame_12_index  ; 
         sequence_numbered_user_input Output_parse_frame_20_data [1] ; 
         uint32_t Output_parse_frame_20_index  ; 
         sequence_numbered_gyroscope_sample Output_parse_frame_30_data [1] ; 
         uint32_t Output_parse_frame_30_index  ; 
         sequence_numbered_stab_config Output_parse_frame_10_data [1] ; 
         uint32_t Output_parse_frame_10_index  ; 
         sequence_numbered_tristate Output_parse_frame_16_data [1] ; 
         uint32_t Output_parse_frame_16_index  ; 
         uint32_t Output_parse_frame_21_data [1] ; 
         uint32_t Output_parse_frame_21_index  ; 
         sequence_numbered_accelerometer_sample Output_parse_frame_34_data [1] ; 
         uint32_t Output_parse_frame_34_index  ; 
         sequence_numbered_pid_config Output_parse_frame_14_data [1] ; 
         uint32_t Output_parse_frame_14_index  ; 
         sequence_numbered_sensors_result Output_parse_frame_29_data [1] ; 
         uint32_t Output_parse_frame_29_index  ; 
         sequence_numbered_rc_input Output_parse_frame_27_data [1] ; 
         uint32_t Output_parse_frame_27_index  ; 
         sequence_numbered_camera_target Output_parse_frame_23_data [1] ; 
         uint32_t Output_parse_frame_23_index  ; 
         sequence_numbered_pid_config Output_parse_frame_4_data [1] ; 
         uint32_t Output_parse_frame_4_index  ; 
         sequence_numbered_xyz_calibration Output_parse_frame_35_data [1] ; 
         uint32_t Output_parse_frame_35_index  ; 
         sequence_numbered_px4io_state Output_parse_frame_49_data [1] ; 
         uint32_t Output_parse_frame_49_index  ; 
         sequence_numbered_user_input_result Output_parse_frame_28_data [1] ; 
         uint32_t Output_parse_frame_28_index  ; 
         sequence_numbered_quadcopter_motors Output_parse_frame_46_data [1] ; 
         uint32_t Output_parse_frame_46_index  ; 
         sequence_numbered_accelerometer_sample Output_parse_frame_37_data [1] ; 
         uint32_t Output_parse_frame_37_index  ; 
         sequence_numbered_control_law Output_parse_frame_26_data [1] ; 
         uint32_t Output_parse_frame_26_index  ; 
         sequence_numbered_xyz_calibration Output_parse_frame_40_data [1] ; 
         uint32_t Output_parse_frame_40_index  ; 
         sequence_numbered_barometer_sample Output_parse_frame_38_data [1] ; 
         uint32_t Output_parse_frame_38_index  ; 
         sequence_numbered_arming_status Output_parse_frame_50_data [1] ; 
         uint32_t Output_parse_frame_50_index  ; 
         sequence_numbered_xyz_calibration Output_parse_frame_41_data [1] ; 
         uint32_t Output_parse_frame_41_index  ; 
         uint32_t Output_parse_frame_0_data [1] ; 
         uint32_t Output_parse_frame_0_index  ; 
         sequence_numbered_att_control_debug Output_parse_frame_47_data [1] ; 
         uint32_t Output_parse_frame_47_index  ; 
         sequence_numbered_pid_config Output_parse_frame_2_data [1] ; 
         uint32_t Output_parse_frame_2_index  ; 
         sequence_numbered_xyz_calibration Output_parse_frame_32_data [1] ; 
         uint32_t Output_parse_frame_32_index  ; 
         sequence_numbered_alt_control_debug Output_parse_frame_48_data [1] ; 
         uint32_t Output_parse_frame_48_index  ; 
         sequence_numbered_stab_config Output_parse_frame_8_data [1] ; 
         uint32_t Output_parse_frame_8_index  ; 
         sequence_numbered_control_modes Output_parse_frame_18_data [1] ; 
         uint32_t Output_parse_frame_18_index  ; 
         sequence_numbered_gyroscope_sample Output_parse_frame_33_data [1] ; 
         uint32_t Output_parse_frame_33_index  ; 
         sequence_numbered_xyz_calibration Output_parse_frame_31_data [1] ; 
         uint32_t Output_parse_frame_31_index  ; 
         sequence_numbered_control_setpoint Output_parse_frame_44_data [1] ; 
         uint32_t Output_parse_frame_44_index  ; 
         sequence_numbered_rgb_led_setting Output_parse_frame_22_data [1] ; 
         uint32_t Output_parse_frame_22_index  ; 
         heartbeat Output_parse_frame_24_data [1] ; 
         uint32_t Output_parse_frame_24_index  ; 
         sequence_numbered_position_sample Output_parse_frame_43_data [1] ; 
         uint32_t Output_parse_frame_43_index  ; 
         uint32_t Output_parse_frame_11_data [1] ; 
         uint32_t Output_parse_frame_11_index  ; 
         uint32_t Output_parse_frame_13_data [1] ; 
         uint32_t Output_parse_frame_13_index  ; 
         uint32_t Output_parse_frame_15_data [1] ; 
         uint32_t Output_parse_frame_15_index  ; 
         uint32_t Output_parse_frame_17_data [1] ; 
         uint32_t Output_parse_frame_17_index  ; 
         uint32_t Output_parse_frame_19_data [1] ; 
         uint32_t Output_parse_frame_19_index  ; 
         sequence_numbered_xyz_calibration Output_parse_frame_36_data [1] ; 
         uint32_t Output_parse_frame_36_index  ; 
         sequence_numbered_magnetometer_sample Output_parse_frame_42_data [1] ; 
         uint32_t Output_parse_frame_42_index  ; 
         sequence_numbered_throttle_ui Output_parse_frame_6_data [1] ; 
         uint32_t Output_parse_frame_6_index  ; 
         sequence_numbered_control_output Output_parse_frame_45_data [1] ; 
         uint32_t Output_parse_frame_45_index  ; 
      } smaccm_controllableVehicleProducerOutput_Input_parse_frame_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_yawRatePidGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_yawRatePidGetReqConsumer_0_data [1] ; 
         uint32_t Output_yawRatePidGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_yawRatePidGetReqConsumer_struct ; 

typedef 
      struct smaccm_frame_datalink_decode_Input_decoder_serial_in_struct { 
         Data_Types__array_96_Unsigned_8_impl Output_decoder_serial_in_0_data [1] ; 
         uint32_t Output_decoder_serial_in_0_index  ; 
      } smaccm_frame_datalink_decode_Input_decoder_serial_in_struct ; 

typedef 
      struct smaccm_fragment_reassembly_Input_receive_msg_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_receive_msg_0_data [1] ; 
         uint32_t Output_receive_msg_0_index  ; 
      } smaccm_fragment_reassembly_Input_receive_msg_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_controlSetpointGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_controlSetpointGetRespProducer_0_data [1] ; 
         uint32_t Output_controlSetpointGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_controlSetpointGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_altitudeRatePidSetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_altitudeRatePidSetReqConsumer_0_data [1] ; 
         uint32_t Output_altitudeRatePidSetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_altitudeRatePidSetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_controlSetpointGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_controlSetpointGetReqConsumer_0_data [1] ; 
         uint32_t Output_controlSetpointGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_controlSetpointGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_controlModesRequestGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_controlModesRequestGetRespProducer_0_data [1] ; 
         uint32_t Output_controlModesRequestGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_controlModesRequestGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_yawPositionPidGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_yawPositionPidGetReqConsumer_0_data [1] ; 
         uint32_t Output_yawPositionPidGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_yawPositionPidGetReqConsumer_struct ; 

typedef 
      struct smaccm_fragment_0x200_Input_fragment_req_0x200_struct { 
         can_message Output_fragment_req_0x200_0_data [1] ; 
         uint32_t Output_fragment_req_0x200_0_index  ; 
      } smaccm_fragment_0x200_Input_fragment_req_0x200_struct ; 

typedef 
      struct smaccm_periodic_camera_injector_Input_camera_req_struct { 
         sequence_numbered_camera_target Output_camera_req_0_data [1] ; 
         uint32_t Output_camera_req_0_index  ; 
      } smaccm_periodic_camera_injector_Input_camera_req_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_armingRequestSetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_armingRequestSetRespProducer_0_data [1] ; 
         uint32_t Output_armingRequestSetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_armingRequestSetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_cameraTargetInputGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_cameraTargetInputGetReqConsumer_0_data [1] ; 
         uint32_t Output_cameraTargetInputGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_cameraTargetInputGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_controlOutputGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_controlOutputGetRespProducer_0_data [1] ; 
         uint32_t Output_controlOutputGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_controlOutputGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_gyroCalibrationGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_gyroCalibrationGetReqConsumer_0_data [1] ; 
         uint32_t Output_gyroCalibrationGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_gyroCalibrationGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_batteryVoltageGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_batteryVoltageGetRespProducer_0_data [1] ; 
         uint32_t Output_batteryVoltageGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_batteryVoltageGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_baroOutputGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_baroOutputGetReqConsumer_0_data [1] ; 
         uint32_t Output_baroOutputGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_baroOutputGetReqConsumer_struct ; 

typedef 
      struct smaccm_thread_period_5ms_periodic_dispatcher_struct { 
         int64_t Output_5ms_data [1] ; 
         uint32_t Output_5ms_index  ; 
      } smaccm_thread_period_5ms_periodic_dispatcher_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_magRawOutputGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_magRawOutputGetReqConsumer_0_data [1] ; 
         uint32_t Output_magRawOutputGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_magRawOutputGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_rgbLedSetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_rgbLedSetRespProducer_0_data [1] ; 
         uint32_t Output_rgbLedSetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_rgbLedSetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_throttleUiGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_throttleUiGetRespProducer_0_data [1] ; 
         uint32_t Output_throttleUiGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_throttleUiGetRespProducer_struct ; 

typedef 
      struct smaccm_fragment_0x200_Input_fragment_complete_0x200_struct { 
         bool Output_fragment_complete_0x200_1_data [1] ; 
         uint32_t Output_fragment_complete_0x200_1_index  ; 
         can_message Output_fragment_complete_0x200_0_data [1] ; 
         uint32_t Output_fragment_complete_0x200_0_index  ; 
      } smaccm_fragment_0x200_Input_fragment_complete_0x200_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_attitudeRollStabGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_attitudeRollStabGetRespProducer_0_data [1] ; 
         uint32_t Output_attitudeRollStabGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_attitudeRollStabGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_batteryVoltageGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_batteryVoltageGetReqConsumer_0_data [1] ; 
         uint32_t Output_batteryVoltageGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_batteryVoltageGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_motorOutputGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_motorOutputGetRespProducer_0_data [1] ; 
         uint32_t Output_motorOutputGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_motorOutputGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_attitudeRollStabSetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_attitudeRollStabSetRespProducer_0_data [1] ; 
         uint32_t Output_attitudeRollStabSetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_attitudeRollStabSetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_controlModesRequestSetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_controlModesRequestSetReqConsumer_0_data [1] ; 
         uint32_t Output_controlModesRequestSetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_controlModesRequestSetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_magOutputGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_magOutputGetRespProducer_0_data [1] ; 
         uint32_t Output_magOutputGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_magOutputGetRespProducer_struct ; 

typedef 
      struct smaccm_frame_datalink_encode_Input_complete_struct { 
         uint32_t unused  ; 
      } smaccm_frame_datalink_encode_Input_complete_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_throttleUiSetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_throttleUiSetRespProducer_0_data [1] ; 
         uint32_t Output_throttleUiSetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_throttleUiSetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_heartbeatProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_heartbeatProducer_0_data [1] ; 
         uint32_t Output_heartbeatProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_heartbeatProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_yawRatePidSetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_yawRatePidSetRespProducer_0_data [1] ; 
         uint32_t Output_yawRatePidSetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_yawRatePidSetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_motorOutputGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_motorOutputGetReqConsumer_0_data [1] ; 
         uint32_t Output_motorOutputGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_motorOutputGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_accelOutputCalibrationGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_accelOutputCalibrationGetReqConsumer_0_data [1] ; 
         uint32_t Output_accelOutputCalibrationGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_accelOutputCalibrationGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_magCalibrationGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_magCalibrationGetReqConsumer_0_data [1] ; 
         uint32_t Output_magCalibrationGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_magCalibrationGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_attitudePitchStabSetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_attitudePitchStabSetReqConsumer_0_data [1] ; 
         uint32_t Output_attitudePitchStabSetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_attitudePitchStabSetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_altitudePositionPidSetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_altitudePositionPidSetRespProducer_0_data [1] ; 
         uint32_t Output_altitudePositionPidSetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_altitudePositionPidSetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_gyroOutputGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_gyroOutputGetReqConsumer_0_data [1] ; 
         uint32_t Output_gyroOutputGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_gyroOutputGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_yawRatePidGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_yawRatePidGetRespProducer_0_data [1] ; 
         uint32_t Output_yawRatePidGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_yawRatePidGetRespProducer_struct ; 

typedef uint8_t Data_Types__array_24_Unsigned_8_impl [24]; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_sensorsOutputGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_sensorsOutputGetRespProducer_0_data [1] ; 
         uint32_t Output_sensorsOutputGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_sensorsOutputGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_controlModesRequestGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_controlModesRequestGetReqConsumer_0_data [1] ; 
         uint32_t Output_controlModesRequestGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_controlModesRequestGetReqConsumer_struct ; 

typedef 
      struct smaccm_fragment_drop_Input_fragment_done_struct { 
         uint32_t unused  ; 
      } smaccm_fragment_drop_Input_fragment_done_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_armingStatusGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_armingStatusGetReqConsumer_0_data [1] ; 
         uint32_t Output_armingStatusGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_armingStatusGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_accelCalibrationGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_accelCalibrationGetReqConsumer_0_data [1] ; 
         uint32_t Output_accelCalibrationGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_accelCalibrationGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_baroOutputGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_baroOutputGetRespProducer_0_data [1] ; 
         uint32_t Output_baroOutputGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_baroOutputGetRespProducer_struct ; 

typedef 
      struct smaccm_frame_datalink_encode_Input_encoder_ct_in_struct { 
         ivory_string_HXCyphertext Output_encoder_ct_in_0_data [1] ; 
         uint32_t Output_encoder_ct_in_0_index  ; 
      } smaccm_frame_datalink_encode_Input_encoder_ct_in_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_magOutputGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_magOutputGetReqConsumer_0_data [1] ; 
         uint32_t Output_magOutputGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_magOutputGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_throttleUiSetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_throttleUiSetReqConsumer_0_data [1] ; 
         uint32_t Output_throttleUiSetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_throttleUiSetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_gyroRawOutputGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_gyroRawOutputGetReqConsumer_0_data [1] ; 
         uint32_t Output_gyroRawOutputGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_gyroRawOutputGetReqConsumer_struct ; 

typedef 
      struct smaccm_fragment_0x200_Input_fragment_abort_0x200_struct { 
         bool Output_fragment_abort_0x200_0_data [1] ; 
         uint32_t Output_fragment_abort_0x200_0_index  ; 
      } smaccm_fragment_0x200_Input_fragment_abort_0x200_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_accelOutputGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_accelOutputGetReqConsumer_0_data [1] ; 
         uint32_t Output_accelOutputGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_accelOutputGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_altitudePositionPidGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_altitudePositionPidGetRespProducer_0_data [1] ; 
         uint32_t Output_altitudePositionPidGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_altitudePositionPidGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_px4ioStateGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_px4ioStateGetReqConsumer_0_data [1] ; 
         uint32_t Output_px4ioStateGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_px4ioStateGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_magCalibrationGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_magCalibrationGetRespProducer_0_data [1] ; 
         uint32_t Output_magCalibrationGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_magCalibrationGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_userInputRequestGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_userInputRequestGetReqConsumer_0_data [1] ; 
         uint32_t Output_userInputRequestGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_userInputRequestGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_rebootSetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_rebootSetReqConsumer_0_data [1] ; 
         uint32_t Output_rebootSetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_rebootSetReqConsumer_struct ; 

typedef 
      struct smaccm_commsecEncodeState_Input_gec_encode_init_struct { 
         uint32_t unused  ; 
      } smaccm_commsecEncodeState_Input_gec_encode_init_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_accelRawOutputGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_accelRawOutputGetReqConsumer_0_data [1] ; 
         uint32_t Output_accelRawOutputGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_accelRawOutputGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_attitudePitchStabGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_attitudePitchStabGetReqConsumer_0_data [1] ; 
         uint32_t Output_attitudePitchStabGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_attitudePitchStabGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_attitudeRollStabGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_attitudeRollStabGetReqConsumer_0_data [1] ; 
         uint32_t Output_attitudeRollStabGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_attitudeRollStabGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_magRawOutputGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_magRawOutputGetRespProducer_0_data [1] ; 
         uint32_t Output_magRawOutputGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_magRawOutputGetRespProducer_struct ; 

typedef 
      struct smaccm_send_transdata_Input_send_translate_struct { 
         ivory_string_UartPacket Output_send_translate_0_data [1] ; 
         uint32_t Output_send_translate_0_index  ; 
      } smaccm_send_transdata_Input_send_translate_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_altitudePositionPidSetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_altitudePositionPidSetReqConsumer_0_data [1] ; 
         uint32_t Output_altitudePositionPidSetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_altitudePositionPidSetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_accelOutputCalibrationGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_accelOutputCalibrationGetRespProducer_0_data [1] ; 
         uint32_t Output_accelOutputCalibrationGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_accelOutputCalibrationGetRespProducer_struct ; 

typedef 
      struct smaccm_commsecEncodeStaticKey_commsecEncodeStaticKey_initializer_struct { 
         Data_Types__array_24_Unsigned_8_impl Output_configureStaticKey_0_data [1] ; 
         uint32_t Output_configureStaticKey_0_index  ; 
      } smaccm_commsecEncodeStaticKey_commsecEncodeStaticKey_initializer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_throttleUiGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_throttleUiGetReqConsumer_0_data [1] ; 
         uint32_t Output_throttleUiGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_throttleUiGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_controlLawGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_controlLawGetReqConsumer_0_data [1] ; 
         uint32_t Output_controlLawGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_controlLawGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_rcInputGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_rcInputGetReqConsumer_0_data [1] ; 
         uint32_t Output_rcInputGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_rcInputGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_attControlDebugGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_attControlDebugGetReqConsumer_0_data [1] ; 
         uint32_t Output_attControlDebugGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_attControlDebugGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_accelOutputGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_accelOutputGetRespProducer_0_data [1] ; 
         uint32_t Output_accelOutputGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_accelOutputGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_sensorsOutputGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_sensorsOutputGetReqConsumer_0_data [1] ; 
         uint32_t Output_sensorsOutputGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_sensorsOutputGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerOutput_Input_parse_frame_2_struct { 
         sequence_numbered_throttle_ui Output_parse_frame_2_5_data [1] ; 
         uint32_t Output_parse_frame_2_5_index  ; 
         uint32_t Output_parse_frame_2_14_data [1] ; 
         uint32_t Output_parse_frame_2_14_index  ; 
         uint32_t Output_parse_frame_2_49_data [1] ; 
         uint32_t Output_parse_frame_2_49_index  ; 
         uint32_t Output_parse_frame_2_18_data [1] ; 
         uint32_t Output_parse_frame_2_18_index  ; 
         uint32_t Output_parse_frame_2_16_data [1] ; 
         uint32_t Output_parse_frame_2_16_index  ; 
         uint32_t Output_parse_frame_2_10_data [1] ; 
         uint32_t Output_parse_frame_2_10_index  ; 
         uint32_t Output_parse_frame_2_29_data [1] ; 
         uint32_t Output_parse_frame_2_29_index  ; 
         uint32_t Output_parse_frame_2_27_data [1] ; 
         uint32_t Output_parse_frame_2_27_index  ; 
         uint32_t Output_parse_frame_2_23_data [1] ; 
         uint32_t Output_parse_frame_2_23_index  ; 
         uint32_t Output_parse_frame_2_25_data [1] ; 
         uint32_t Output_parse_frame_2_25_index  ; 
         uint32_t Output_parse_frame_2_12_data [1] ; 
         uint32_t Output_parse_frame_2_12_index  ; 
         uint32_t Output_parse_frame_2_43_data [1] ; 
         uint32_t Output_parse_frame_2_43_index  ; 
         uint32_t Output_parse_frame_2_45_data [1] ; 
         uint32_t Output_parse_frame_2_45_index  ; 
         uint32_t Output_parse_frame_2_47_data [1] ; 
         uint32_t Output_parse_frame_2_47_index  ; 
         uint32_t Output_parse_frame_2_41_data [1] ; 
         uint32_t Output_parse_frame_2_41_index  ; 
         uint32_t Output_parse_frame_2_32_data [1] ; 
         uint32_t Output_parse_frame_2_32_index  ; 
         uint32_t Output_parse_frame_2_34_data [1] ; 
         uint32_t Output_parse_frame_2_34_index  ; 
         uint32_t Output_parse_frame_2_36_data [1] ; 
         uint32_t Output_parse_frame_2_36_index  ; 
         uint32_t Output_parse_frame_2_38_data [1] ; 
         uint32_t Output_parse_frame_2_38_index  ; 
         uint32_t Output_parse_frame_2_30_data [1] ; 
         uint32_t Output_parse_frame_2_30_index  ; 
         uint32_t Output_parse_frame_2_50_data [1] ; 
         uint32_t Output_parse_frame_2_50_index  ; 
         sequence_numbered_user_input Output_parse_frame_2_19_data [1] ; 
         uint32_t Output_parse_frame_2_19_index  ; 
         sequence_numbered_stab_config Output_parse_frame_2_9_data [1] ; 
         uint32_t Output_parse_frame_2_9_index  ; 
         sequence_numbered_pid_config Output_parse_frame_2_11_data [1] ; 
         uint32_t Output_parse_frame_2_11_index  ; 
         sequence_numbered_reboot Output_parse_frame_2_0_data [1] ; 
         uint32_t Output_parse_frame_2_0_index  ; 
         sequence_numbered_control_modes Output_parse_frame_2_17_data [1] ; 
         uint32_t Output_parse_frame_2_17_index  ; 
         sequence_numbered_pid_config Output_parse_frame_2_1_data [1] ; 
         uint32_t Output_parse_frame_2_1_index  ; 
         sequence_numbered_rgb_led_setting Output_parse_frame_2_21_data [1] ; 
         uint32_t Output_parse_frame_2_21_index  ; 
         sequence_numbered_stab_config Output_parse_frame_2_7_data [1] ; 
         uint32_t Output_parse_frame_2_7_index  ; 
         uint32_t Output_parse_frame_2_2_data [1] ; 
         uint32_t Output_parse_frame_2_2_index  ; 
         uint32_t Output_parse_frame_2_4_data [1] ; 
         uint32_t Output_parse_frame_2_4_index  ; 
         uint32_t Output_parse_frame_2_6_data [1] ; 
         uint32_t Output_parse_frame_2_6_index  ; 
         uint32_t Output_parse_frame_2_8_data [1] ; 
         uint32_t Output_parse_frame_2_8_index  ; 
         sequence_numbered_tristate Output_parse_frame_2_15_data [1] ; 
         uint32_t Output_parse_frame_2_15_index  ; 
         uint32_t Output_parse_frame_2_44_data [1] ; 
         uint32_t Output_parse_frame_2_44_index  ; 
         uint32_t Output_parse_frame_2_28_data [1] ; 
         uint32_t Output_parse_frame_2_28_index  ; 
         uint32_t Output_parse_frame_2_20_data [1] ; 
         uint32_t Output_parse_frame_2_20_index  ; 
         uint32_t Output_parse_frame_2_26_data [1] ; 
         uint32_t Output_parse_frame_2_26_index  ; 
         uint32_t Output_parse_frame_2_22_data [1] ; 
         uint32_t Output_parse_frame_2_22_index  ; 
         uint32_t Output_parse_frame_2_24_data [1] ; 
         uint32_t Output_parse_frame_2_24_index  ; 
         uint32_t Output_parse_frame_2_46_data [1] ; 
         uint32_t Output_parse_frame_2_46_index  ; 
         uint32_t Output_parse_frame_2_48_data [1] ; 
         uint32_t Output_parse_frame_2_48_index  ; 
         uint32_t Output_parse_frame_2_33_data [1] ; 
         uint32_t Output_parse_frame_2_33_index  ; 
         uint32_t Output_parse_frame_2_40_data [1] ; 
         uint32_t Output_parse_frame_2_40_index  ; 
         uint32_t Output_parse_frame_2_42_data [1] ; 
         uint32_t Output_parse_frame_2_42_index  ; 
         uint32_t Output_parse_frame_2_35_data [1] ; 
         uint32_t Output_parse_frame_2_35_index  ; 
         uint32_t Output_parse_frame_2_37_data [1] ; 
         uint32_t Output_parse_frame_2_37_index  ; 
         uint32_t Output_parse_frame_2_31_data [1] ; 
         uint32_t Output_parse_frame_2_31_index  ; 
         uint32_t Output_parse_frame_2_39_data [1] ; 
         uint32_t Output_parse_frame_2_39_index  ; 
         sequence_numbered_pid_config Output_parse_frame_2_3_data [1] ; 
         uint32_t Output_parse_frame_2_3_index  ; 
         sequence_numbered_pid_config Output_parse_frame_2_13_data [1] ; 
         uint32_t Output_parse_frame_2_13_index  ; 
      } smaccm_controllableVehicleConsumerOutput_Input_parse_frame_2_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_userInputRequestSetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_userInputRequestSetReqConsumer_0_data [1] ; 
         uint32_t Output_userInputRequestSetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_userInputRequestSetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_attControlDebugGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_attControlDebugGetRespProducer_0_data [1] ; 
         uint32_t Output_attControlDebugGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_attControlDebugGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_packedStatusGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_packedStatusGetRespProducer_0_data [1] ; 
         uint32_t Output_packedStatusGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_packedStatusGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_altitudeRatePidSetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_altitudeRatePidSetRespProducer_0_data [1] ; 
         uint32_t Output_altitudeRatePidSetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_altitudeRatePidSetRespProducer_struct ; 

typedef 
      struct smaccm_commsecDecodeState_Input_cyphertext_decode_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_cyphertext_decode_0_data [1] ; 
         uint32_t Output_cyphertext_decode_0_index  ; 
      } smaccm_commsecDecodeState_Input_cyphertext_decode_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_packedStatusGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_packedStatusGetReqConsumer_0_data [1] ; 
         uint32_t Output_packedStatusGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_packedStatusGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_userInputGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_userInputGetRespProducer_0_data [1] ; 
         uint32_t Output_userInputGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_userInputGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_armingStatusGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_armingStatusGetRespProducer_0_data [1] ; 
         uint32_t Output_armingStatusGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_armingStatusGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_gyroOutputGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_gyroOutputGetRespProducer_0_data [1] ; 
         uint32_t Output_gyroOutputGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_gyroOutputGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_gpsOutputGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_gpsOutputGetReqConsumer_0_data [1] ; 
         uint32_t Output_gpsOutputGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_gpsOutputGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_rebootSetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_rebootSetRespProducer_0_data [1] ; 
         uint32_t Output_rebootSetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_rebootSetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_altControlDebugGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_altControlDebugGetRespProducer_0_data [1] ; 
         uint32_t Output_altControlDebugGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_altControlDebugGetRespProducer_struct ; 

typedef 
      struct smaccm_to_hx_Input_unpack_struct { 
         uint8_t Output_unpack_0_data [255] ; 
         uint32_t Output_unpack_0_index  ; 
      } smaccm_to_hx_Input_unpack_struct ; 

typedef 
      struct smaccm_can_node_Input_abortHandler_struct { 
         uint32_t unused  ; 
      } smaccm_can_node_Input_abortHandler_struct ; 

typedef 
      struct smaccm_can_node_Input_sender_struct { 
         uint32_t unused  ; 
      } smaccm_can_node_Input_sender_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_gyroRawOutputGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_gyroRawOutputGetRespProducer_0_data [1] ; 
         uint32_t Output_gyroRawOutputGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_gyroRawOutputGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_armingRequestGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_armingRequestGetReqConsumer_0_data [1] ; 
         uint32_t Output_armingRequestGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_armingRequestGetReqConsumer_struct ; 

typedef 
      struct smaccm_commsecEncodeState_Input_plaintext_encode_struct { 
         Data_Types__array_96_Unsigned_8_impl Output_plaintext_encode_0_data [1] ; 
         uint32_t Output_plaintext_encode_0_index  ; 
      } smaccm_commsecEncodeState_Input_plaintext_encode_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_rgbLedGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_rgbLedGetReqConsumer_0_data [1] ; 
         uint32_t Output_rgbLedGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_rgbLedGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_attitudeRollStabSetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_attitudeRollStabSetReqConsumer_0_data [1] ; 
         uint32_t Output_attitudeRollStabSetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_attitudeRollStabSetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_gyroCalibrationGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_gyroCalibrationGetRespProducer_0_data [1] ; 
         uint32_t Output_gyroCalibrationGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_gyroCalibrationGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_userInputGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_userInputGetReqConsumer_0_data [1] ; 
         uint32_t Output_userInputGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_userInputGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_yawPositionPidGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_yawPositionPidGetRespProducer_0_data [1] ; 
         uint32_t Output_yawPositionPidGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_yawPositionPidGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_attitudePitchStabSetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_attitudePitchStabSetRespProducer_0_data [1] ; 
         uint32_t Output_attitudePitchStabSetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_attitudePitchStabSetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_userInputRequestGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_userInputRequestGetRespProducer_0_data [1] ; 
         uint32_t Output_userInputRequestGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_userInputRequestGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_gpsOutputGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_gpsOutputGetRespProducer_0_data [1] ; 
         uint32_t Output_gpsOutputGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_gpsOutputGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_armingRequestSetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_armingRequestSetReqConsumer_0_data [1] ; 
         uint32_t Output_armingRequestSetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_armingRequestSetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_gyroOutputCalibrationGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_gyroOutputCalibrationGetRespProducer_0_data [1] ; 
         uint32_t Output_gyroOutputCalibrationGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_gyroOutputCalibrationGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_cameraTargetInputGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_cameraTargetInputGetRespProducer_0_data [1] ; 
         uint32_t Output_cameraTargetInputGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_cameraTargetInputGetRespProducer_struct ; 

typedef 
      struct smaccm_uart_Input_send_struct { 
         uint32_t unused  ; 
      } smaccm_uart_Input_send_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_altControlDebugGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_altControlDebugGetReqConsumer_0_data [1] ; 
         uint32_t Output_altControlDebugGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_altControlDebugGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_rcInputGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_rcInputGetRespProducer_0_data [1] ; 
         uint32_t Output_rcInputGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_rcInputGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_altitudePositionPidGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_altitudePositionPidGetReqConsumer_0_data [1] ; 
         uint32_t Output_altitudePositionPidGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_altitudePositionPidGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_altitudeRatePidGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_altitudeRatePidGetRespProducer_0_data [1] ; 
         uint32_t Output_altitudeRatePidGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_altitudeRatePidGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_armingRequestGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_armingRequestGetRespProducer_0_data [1] ; 
         uint32_t Output_armingRequestGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_armingRequestGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_rgbLedSetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_rgbLedSetReqConsumer_0_data [1] ; 
         uint32_t Output_rgbLedSetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_rgbLedSetReqConsumer_struct ; 

typedef 
      struct smaccm_commsecDecodeStaticKey_commsecDecodeStaticKey_initializer_struct { 
         Data_Types__array_24_Unsigned_8_impl Output_configureStaticKey_2_0_data [1] ; 
         uint32_t Output_configureStaticKey_2_0_index  ; 
      } smaccm_commsecDecodeStaticKey_commsecDecodeStaticKey_initializer_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_gyroOutputCalibrationGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_gyroOutputCalibrationGetReqConsumer_0_data [1] ; 
         uint32_t Output_gyroOutputCalibrationGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_gyroOutputCalibrationGetReqConsumer_struct ; 

typedef 
      struct smaccm_frameBuffer_Input_push_struct { 
         uint32_t unused  ; 
      } smaccm_frameBuffer_Input_push_struct ; 

typedef 
      struct smaccm_controllableVehicleConsumerInput_Input_controlOutputGetReqConsumer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_controlOutputGetReqConsumer_0_data [1] ; 
         uint32_t Output_controlOutputGetReqConsumer_0_index  ; 
      } smaccm_controllableVehicleConsumerInput_Input_controlOutputGetReqConsumer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_controlModesRequestSetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_controlModesRequestSetRespProducer_0_data [1] ; 
         uint32_t Output_controlModesRequestSetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_controlModesRequestSetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_rgbLedGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_rgbLedGetRespProducer_0_data [1] ; 
         uint32_t Output_rgbLedGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_rgbLedGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_controlLawGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_controlLawGetRespProducer_0_data [1] ; 
         uint32_t Output_controlLawGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_controlLawGetRespProducer_struct ; 

typedef 
      struct smaccm_controllableVehicleProducerInput_Input_px4ioStateGetRespProducer_struct { 
         Data_Types__array_80_Unsigned_8_impl Output_px4ioStateGetRespProducer_0_data [1] ; 
         uint32_t Output_px4ioStateGetRespProducer_0_index  ; 
      } smaccm_controllableVehicleProducerInput_Input_px4ioStateGetRespProducer_struct ; 

typedef 
      struct smaccm_Data_Types__array_80_Unsigned_8_impl_container { 
         Data_Types__array_80_Unsigned_8_impl f  ; 
      } smaccm_Data_Types__array_80_Unsigned_8_impl_container ; 

typedef 
      struct smaccm_Data_Types__array_96_Unsigned_8_impl_container { 
         Data_Types__array_96_Unsigned_8_impl f  ; 
      } smaccm_Data_Types__array_96_Unsigned_8_impl_container ; 

typedef 
      struct smaccm_Data_Types__array_24_Unsigned_8_impl_container { 
         Data_Types__array_24_Unsigned_8_impl f  ; 
      } smaccm_Data_Types__array_24_Unsigned_8_impl_container ; 

/* endif for: #ifndef __SMACCM_sys_impl_Instance_types__H */
#endif

/**************************************************************************
  End of autogenerated file: smaccm_sys_impl_types.h
 **************************************************************************/

