/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __IVORY_SERIALIZE_H__
#define __IVORY_SERIALIZE_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory_serialize_prim.h>
#include "ivory.h"
void ibool_get_le(const uint8_t *n_var0, uint32_t n_var1, bool *n_var2);
void ibool_get_be(const uint8_t *n_var0, uint32_t n_var1, bool *n_var2);
void ibool_set_le(uint8_t *n_var0, uint32_t n_var1, const bool *n_var2);
void ibool_set_be(uint8_t *n_var0, uint32_t n_var1, const bool *n_var2);

#ifdef __cplusplus
}
#endif
#endif /* __IVORY_SERIALIZE_H__ */