/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __PID_STATE_TYPES_H__
#define __PID_STATE_TYPES_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "ivory_serialize.h"
typedef struct pid_state { float i_state;
                           float d_state;
                           bool d_reset;
                           float p_last;
                           float d_last;
} pid_state;
void pid_state_get_le(const uint8_t *n_var0, uint32_t n_var1, struct pid_state *n_var2);
void pid_state_get_be(const uint8_t *n_var0, uint32_t n_var1, struct pid_state *n_var2);
void pid_state_set_le(uint8_t *n_var0, uint32_t n_var1, const struct pid_state *n_var2);
void pid_state_set_be(uint8_t *n_var0, uint32_t n_var1, const struct pid_state *n_var2);

#ifdef __cplusplus
}
#endif
#endif /* __PID_STATE_TYPES_H__ */