/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.2
 */
#ifndef __COMMON_H__
#define __COMMON_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
struct LOIConfig {
    uint16_t vehicleType;
    uint16_t vehicleSubType;
    int32_t vehicleId;
} __attribute__((__packed__));

// Modified: MWW
#include <stdio.h>
int32_t doCall(struct LOIConfig *ivoryConfig);

#ifdef __cplusplus
}
#endif
#endif /* __COMMON_H__ */