/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "output_UART_in_Server_put_pt_data_monitor.h"

void callback_output_UART_in_Server_put_pt_data_2(const uint8_t n_var0[80U])
{
    //UART_in_Server_put_pt_data(n_var0);
    Decrypt_write_send_gidl(n_var0);
}
