#ifndef __SMACCM_test1_impl_Instance_types__H
#define __SMACCM_test1_impl_Instance_types__H

/**************************************************************************
  Copyright (c) 2013, 2014 Rockwell Collins and the University of Minnesota.
  Developed with the sponsorship of the Defense Advanced Research Projects Agency (DARPA).

  Permission is hereby granted, free of charge, to any person obtaining a copy of this data,
  including any software or models in source or binary form, as well as any drawings, specifications, 
  and documentation (collectively "the Data"), to deal in the Data without restriction, including 
  without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
  and/or sell copies of the Data, and to permit persons to whom the Data is furnished to do so, 
  subject to the following conditions: 

  The above copyright notice and this permission notice shall be included in all copies or
  substantial portions of the Data.

  THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
  LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
  IN NO EVENT SHALL THE AUTHORS, SPONSORS, DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE LIABLE 
  FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE DATA. 

 **************************************************************************/


/**************************************************************************

   File: C:\docs\git_smaccm\smaccm\models\Trusted_Build_Test\test1\include\smaccm_test1_impl_types.h
   Created on: 2015/03/09 10:08:02
   using Dulcimer AADL system build tool suite 

   ***AUTOGENERATED CODE: DO NOT MODIFY***

  This file contains the datatypes used for communications between 
  AADL components as defined in the system implementation test1_impl_Instance.

 **************************************************************************/

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#ifndef smaccm_uint32_t_struct_1
typedef 
      struct { 
         uint32_t f [1] ; 
      } smaccm_uint32_t_struct_1 ; 
#else 
#warning Type: smaccm_uint32_t_struct_1 is not being defined by AADL but by an external source. 
#endif 
 

#ifndef smaccm_uint32_t_struct_0
typedef 
      struct { 
         uint32_t f [0] ; 
      } smaccm_uint32_t_struct_0 ; 
#else 
#warning Type: smaccm_uint32_t_struct_0 is not being defined by AADL but by an external source. 
#endif 
 

/* endif for: #ifndef __SMACCM_test1_impl_Instance_types__H */
#endif

/**************************************************************************
  End of autogenerated file: smaccm_test1_impl_types.h
 **************************************************************************/

