/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __UART_OUT_H__
#define __UART_OUT_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "commsecEncodeStaticKey_monitor.h"
#include "input_Server_UART_out_get_pt_data_monitor.h"
#include "input_UART_hw_UART_out_get_bool_monitor.h"
#include "ivory.h"
#include "smaccm_Encrypt.h"

#ifdef __cplusplus
}
#endif
#endif /* __UART_OUT_H__ */
