/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __CANDRIVERTYPES_H__
#define __CANDRIVERTYPES_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"

#ifdef __cplusplus
}
#endif
#endif /* __CANDRIVERTYPES_H__ */
