/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __REBOOT_REQ_TYPES_H__
#define __REBOOT_REQ_TYPES_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "ivory_serialize.h"
#include "reboot_magic_types.h"
typedef struct reboot_req { uint32_t magic;
} reboot_req;
void reboot_req_get_le(const uint8_t *n_var0, uint32_t n_var1, struct reboot_req *n_var2);
void reboot_req_get_be(const uint8_t *n_var0, uint32_t n_var1, struct reboot_req *n_var2);
void reboot_req_set_le(uint8_t *n_var0, uint32_t n_var1, const struct reboot_req *n_var2);
void reboot_req_set_be(uint8_t *n_var0, uint32_t n_var1, const struct reboot_req *n_var2);

#ifdef __cplusplus
}
#endif
#endif /* __REBOOT_REQ_TYPES_H__ */