/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.4
 */
#ifndef __SMACCM_CAN_MODULE_H__
#define __SMACCM_CAN_MODULE_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "tb_CAN_Framing.h"

#ifdef __cplusplus
}
#endif
#endif /* __SMACCM_CAN_MODULE_H__ */
