/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "input_Decrypt_read_uart2self_monitor.h"

void callback_input_Decrypt_read_uart2self_handler(const struct SMACCM_DATA__UART_Packet_i *n_var0)
{
    callback_from_smaccm_uart_2(n_var0);
}