/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __COMMSECDECODESTATICKEY_MONITOR_H__
#define __COMMSECDECODESTATICKEY_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "commsecDecodeState_monitor.h"
#include "hxstream_state_module.h"
#include "ivory.h"
#include "ivory_serialize.h"
#include "smaccm_UART_module.h"
#include "towerUartDeps.h"
void callback_configureStaticKey(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __COMMSECDECODESTATICKEY_MONITOR_H__ */