/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __INPUT_DECRYPT_READ_UART2SELF_MONITOR_H__
#define __INPUT_DECRYPT_READ_UART2SELF_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "from_smaccm_uart_monitor.h"
#include "hxstream_state_module.h"
#include "ivory.h"
#include "ivory_serialize.h"
#include "smaccm_UART_module.h"
#include "towerUartDeps.h"
void callback_input_Decrypt_read_uart2self_handler(const struct SMACCM_DATA__UART_Packet_i *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __INPUT_DECRYPT_READ_UART2SELF_MONITOR_H__ */