/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __OUTPUT_DECRYPT_WRITE_SEND_GIDL_MONITOR_H__
#define __OUTPUT_DECRYPT_WRITE_SEND_GIDL_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
void callback_output_Decrypt_write_send_gidl_2(const uint8_t n_var0[80U]);

#ifdef __cplusplus
}
#endif
#endif /* __OUTPUT_DECRYPT_WRITE_SEND_GIDL_MONITOR_H__ */