/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.4
 */
#ifndef __CAN_FRAMING_H__
#define __CAN_FRAMING_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "input_tb_CAN_Framing_read_server2self_monitor.h"
#include "input_tb_CAN_Framing_read_can2self_frame_monitor.h"
#include "input_tb_CAN_Framing_read_can2self_status_monitor.h"
#include <tb_CAN_Framing.h>
void component_entry(const int64_t *n_var0);
void component_init(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __CAN_FRAMING_H__ */
