/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __OUTPUT_TB_SELF2CAN_ENQUEUE_MONITOR_H__
#define __OUTPUT_TB_SELF2CAN_ENQUEUE_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "smaccm_can_module.h"
#include "ivory_serialize.h"
#include "canDriverTypes.h"
void callback_output_tb_self2can_enqueue_2(const struct SMACCM_DATA__CAN_Frame_i *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __OUTPUT_TB_SELF2CAN_ENQUEUE_MONITOR_H__ */
