/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TO_SMACCM_CAN_MONITOR_H__
#define __TO_SMACCM_CAN_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "smaccm_can_module.h"
#include "ivory_serialize.h"
#include "canDriverTypes.h"
#include "output_tb_self2can_enqueue_monitor.h"
void callback_to_smaccm_can_2(const struct can_message *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __TO_SMACCM_CAN_MONITOR_H__ */
