/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.2
 */
#include <compbcompb.h>
#include <smaccm_compb.h>

void aadl_do_doCall(LOIConfig* n_var0, int32_t *output)
{
    *&n_var0->vehicletype = (uint16_t) 7U;
    *output = (int32_t) 42;
}