/**************************************************************************
  Copyright (c) 2013-2016 Rockwell Collins and the University of
  Minnesota. Developed with the sponsorship of the Defense Advanced
  Research Projects Agency (DARPA).

  Permission is hereby granted, free of charge, to any person
  obtaining a copy of this data, including any software or models
  in source or binary form, as well as any drawings,
  specifications, and documentation (collectively "the Data"), to
  deal in the Data without restriction, including without
  limitation the rights to use, copy, modify, merge, publish,
  distribute, sublicense, and/or sell copies of the Data, and to
  permit persons to whom the Data is furnished to do so, subject to
  the following conditions:

  The above copyright notice and this permission notice shall be
  included in all copies or substantial portions of the Data.

  THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS, SPONSORS,
  DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
  CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
  CONNECTION WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE
  DATA.
 **************************************************************************/

/**************************************************************************

  ***AUTOGENERATED CODE: DO NOT MODIFY***

  Implementing a Monitor of type SMACCM_DATA__GIDL with a queue size of 
  1. The input port that will be calling dequeue and receiving notifications 
  is tb_Server_framing2self. The output port set follows:

    c.sourcePort


 **************************************************************************/

#include <stdio.h>
#include <stdbool.h>
#include <camkes.h>
#include <tb_smaccmpilot_tk1_types.h>

tb_SMACCM_DATA__GIDL_container contents[1];
static uint32_t front = 0;
static uint32_t length = 0;

static bool is_full(void) {
  return length == 1;
}

static bool is_empty(void) {
  return length == 0;
}
bool deq_dequeue(SMACCM_DATA__GIDL * m) {
  MUTEXOP(q_lock())
  if (is_empty()) {
    MUTEXOP(q_unlock())
    return false;
  } else {
    *((tb_SMACCM_DATA__GIDL_container *)m) = contents[front];
    front = (front + 1) % 1;
    length--;
    MUTEXOP(q_unlock())
    return true;
  }
}

bool enq_enqueue(const SMACCM_DATA__GIDL * m) {
  MUTEXOP(q_lock())
  if (is_full()) {
    MUTEXOP(q_unlock())
    #ifdef CONFIG_APP_SMACCMPILOT_TK1_TB_DEBUG
    fprintf(stderr,"Monitor tb_Server_framing2self is full!\n");
    #endif 
    return false;
  } else {
    contents[(front + length) % 1] = *((tb_SMACCM_DATA__GIDL_container *)m);
    length++;
    qd_emit();
    MUTEXOP(q_unlock())
    return true;
  }
}
