/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "Camera_VM.h"

void component_entry(void)
{
    int64_t n_local0 = (int64_t) 0;
    int64_t *n_ref1 = &n_local0;
    
    return;
}

void component_init(void)
{
    int64_t n_local0 = (int64_t) 0;
    int64_t *n_ref1 = &n_local0;
}