/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __COMMSECENCODESTATICKEY_MONITOR_H__
#define __COMMSECENCODESTATICKEY_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "commsecEncodeState_monitor.h"
#include "hx_cyphertext.h"
#include "ivory.h"
void callback_configureStaticKey(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __COMMSECENCODESTATICKEY_MONITOR_H__ */