/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __ENCRYPT_H__
#define __ENCRYPT_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <smaccm_Encrypt.h>
#include "commsecEncodeStaticKey_monitor.h"
#include "input_Encrypt_read_server2self_monitor.h"
#include "input_Encrypt_read_uart2self_monitor.h"
#include "ivory.h"
void component_entry(const int64_t *n_var0);
void component_init(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __ENCRYPT_H__ */