/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __INPUT_ENCRYPT_READ_UART2SELF_MONITOR_H__
#define __INPUT_ENCRYPT_READ_UART2SELF_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "frame_datalink_encode_monitor.h"
#include "hx_cyphertext.h"
#include "ivory.h"
#include "smaccm_UART_module.h"
#include "towerUartDeps.h"
void callback_input_Encrypt_read_uart2self_handler(const bool *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __INPUT_ENCRYPT_READ_UART2SELF_MONITOR_H__ */