/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.4
 */
#ifndef __SEND_TRANSDATA_MONITOR_H__
#define __SEND_TRANSDATA_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "hx_cyphertext.h"
#include "smaccm_UART_module.h"
#include "towerUartDeps.h"
#include "to_smaccm_uart_monitor.h"
void callback_send_translate(const struct ivory_string_HXCyphertext *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __SEND_TRANSDATA_MONITOR_H__ */
