/**************************************************************************
  Copyright (c) 2013, 2014 Rockwell Collins and the University of Minnesota.
  Developed with the sponsorship of the Defense Advanced Research Projects Agency (DARPA).

  Permission is hereby granted, free of charge, to any person obtaining a copy of this data,
  including any software or models in source or binary form, as well as any drawings, specifications, 
  and documentation (collectively "the Data"), to deal in the Data without restriction, including 
  without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
  and/or sell copies of the Data, and to permit persons to whom the Data is furnished to do so, 
  subject to the following conditions: 

  The above copyright notice and this permission notice shall be included in all copies or
  substantial portions of the Data.

  THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
  LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
  IN NO EVENT SHALL THE AUTHORS, SPONSORS, DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE LIABLE 
  FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE DATA. 

 **************************************************************************/


/**************************************************************************

   File: C:\docs\git_smaccm\smaccm\models\Trusted_Build_Test\test0\components\dispatchers\src\smaccm_dispatcher_sender.c
   Created on: 2014/09/10 18:16:17
   using Dulcimer AADL system build tool suite 

   ***AUTOGENERATED CODE: DO NOT MODIFY***

  This C file contains the dispatcher functions for the 'active' thread 
  sender.  There is no direct interaction between the functionality in 
  this file and user-level code.  Instead, this file interacts with the 
  aadl-generated C file for passive components and the CAmkES generated
  component skeleton.

  This file contains: 
  	1.) The main loop for the control thread to dispatch to 
  		components
  	2.) The dispatcher functions for all passive components.
  	3.) The shared data for any of the active thread send/receive ports.
  	4.) The receiver functions to store messages and wake up the 
  		control thread.
  	5.) The sender functions for other "active" components.


 **************************************************************************/


#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "smaccm_sender.h"

void run() {
	// initialization routines ... skipped for now.

	// initial lock to await dispatch input.
	smaccm_dispatch_mutex_lock();

	for(;;) {
		smaccm_dispatch_mutex_lock();


		// drain the queues 
		if (smaccm_occurred_periodic_100_ms) {
			smaccm_occurred_periodic_100_ms = false;
			smaccm_periodic_100_ms_dispatcher( &smaccm_time_periodic_100_ms);

		}

	}
}

void smaccm_periodic_100_ms_dispatcher(uint32_t * periodic_100_ms ) {

	// make the call: 
	sender_inst_smaccm_periodic_100_ms_dispatcher(periodic_100_ms, 
);

	// invoke any resulting `send' operations
	uint32_t smaccm_it; 

}


// Subsequent passive dispatchers after initial dispatch 


// Functions for managing event queues 
// Functions for managing input dispatchers 
/**************************************************************************
  End of autogenerated file: C:\docs\git_smaccm\smaccm\models\Trusted_Build_Test\test0\components\dispatchers\src\smaccm_dispatcher_sender.c
 **************************************************************************/
