/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "output_tb_self2uart_enqueue_monitor.h"

void callback_output_tb_self2uart_enqueue_2(const struct SMACCM_DATA__UART_Packet_i *n_var0)
{
    tb_self2uart_enqueue(n_var0);
}
