/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "input_CAN_framing_read_fragment_reasembly_monitor.h"

void callback_input_CAN_framing_read_fragment_reasembly_handler(const struct SMACCM_DATA__CAN_Frame_i *n_var0)
{
    callback_receive_msg(n_var0);
}
