/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "input_CAN_framing_read_from_server_monitor.h"

void callback_input_CAN_framing_read_from_server_handler(const uint8_t n_var0[80U])
{
    callback_new_msg(n_var0);
}