/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.4
 */
#include "input_tb_CAN_Framing_read_server2self_monitor.h"

void callback_input_tb_CAN_Framing_read_server2self_handler(const uint8_t n_var0[80U])
{
    callback_new_msg(n_var0);
}
