/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "output_CAN_CAN_hw_put_can_message_monitor.h"
#include "smaccm_CAN_Framing.h"

void callback_output_CAN_CAN_hw_put_can_message_2(const struct can_message *n_var0)
{
    struct SMACCM_DATA__CAN_Frame_i smaccm_can_frame = {};
    smaccm_can_frame.id = n_var0->can_message_id;
    smaccm_can_frame.buf_len = n_var0->can_message_len;
    memcpy(smaccm_can_frame.buf, n_var0->can_message_buf, n_var0->can_message_len);

    CAN_Framing_write_self2can_request(&smaccm_can_frame);
}
