/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.4
 */
#include "to_smaccm_can_monitor.h"

void callback_to_smaccm_can_2(const struct can_message *n_var0)
{
    uint32_t n_deref0 = n_var0->can_message_id;
    int32_t n_deref1 = n_var0->can_message_len;
    struct SMACCM_DATA__CAN_Frame_i n_local2 = {.id =n_deref0, .buf_len =(uint8_t) ((bool) ((bool) (n_deref1 <= (int32_t) UINT8_MAX) && (bool) (n_deref1 >= (int32_t) 0)) ? (uint8_t) n_deref1 : 0)};
    struct SMACCM_DATA__CAN_Frame_i *n_ref3 = &n_local2;
    
    if (n_ref3->buf != n_var0->can_message_buf)
        memcpy(n_ref3->buf, n_var0->can_message_buf, sizeof(uint8_t [8U]));
    else
        COMPILER_ASSERTS(false);
    callback_output_tb_CAN_Framing_write_self2can_2(n_ref3);
}
