/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "xyz_types.h"

void xyz_get_le(const uint8_t *n_var0, uint32_t n_var1, struct xyz *n_var2)
{
    ivory_serialize_unpack_float_le(n_var0, n_var1, &n_var2->x);
    ivory_serialize_unpack_float_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 4U), &n_var2->y);
    ivory_serialize_unpack_float_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 8U), &n_var2->z);
}

void xyz_get_be(const uint8_t *n_var0, uint32_t n_var1, struct xyz *n_var2)
{
    ivory_serialize_unpack_float_be(n_var0, n_var1, &n_var2->x);
    ivory_serialize_unpack_float_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 4U), &n_var2->y);
    ivory_serialize_unpack_float_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 8U), &n_var2->z);
}

void xyz_set_le(uint8_t *n_var0, uint32_t n_var1, const struct xyz *n_var2)
{
    ivory_serialize_pack_float_le(n_var0, n_var1, &n_var2->x);
    ivory_serialize_pack_float_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 4U), &n_var2->y);
    ivory_serialize_pack_float_le(n_var0, (uint32_t) (n_var1 + (uint32_t) 8U), &n_var2->z);
}

void xyz_set_be(uint8_t *n_var0, uint32_t n_var1, const struct xyz *n_var2)
{
    ivory_serialize_pack_float_be(n_var0, n_var1, &n_var2->x);
    ivory_serialize_pack_float_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 4U), &n_var2->y);
    ivory_serialize_pack_float_be(n_var0, (uint32_t) (n_var1 + (uint32_t) 8U), &n_var2->z);
}