apps-$(CONFIG_APP_SMACCMPILOT_TK1) += smaccmpilot-tk1
smaccmpilot-tk1: libsel4 libmuslc libsel4platsupport libsel4muslccamkes \
                 libsel4camkes libsel4sync libsel4debug libsel4bench \
                 libsel4simple libsel4allocman libsel4arm-vmm libsel4vka \
                 libsel4vspace libelf libsel4utils libutils \
                 libsel4simple-default libcpio
