/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#include "input_Server_read_camera_data_monitor.h"
#include "smaccm_Server.h"

void callback_input_Server_read_camera_data_handler(const struct SMACCM_DATA__Camera_Bounding_Box_i *n_var0)
{
    callback_cameraDataRx(n_var0);
}
