/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.3
 */
#ifndef __MAGNETOMETER_SAMPLE_TYPES_H__
#define __MAGNETOMETER_SAMPLE_TYPES_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "ivory_serialize.h"
#include "time_micros_types.h"
#include "xyz_types.h"
typedef struct magnetometer_sample { bool initfail;
                                     bool samplefail;
                                     bool calibrated;
                                     struct xyz sample;
                                     int64_t time;
} magnetometer_sample;
void magnetometer_sample_get_le(const uint8_t *n_var0, uint32_t n_var1, struct magnetometer_sample *n_var2);
void magnetometer_sample_get_be(const uint8_t *n_var0, uint32_t n_var1, struct magnetometer_sample *n_var2);
void magnetometer_sample_set_le(uint8_t *n_var0, uint32_t n_var1, const struct magnetometer_sample *n_var2);
void magnetometer_sample_set_be(uint8_t *n_var0, uint32_t n_var1, const struct magnetometer_sample *n_var2);

#ifdef __cplusplus
}
#endif
#endif /* __MAGNETOMETER_SAMPLE_TYPES_H__ */